import { notFound } from "next/navigation";
import { ElectronicsReview } from "@/components/storefront/sector-design/electronics-review";
import { isDesignId, defaultContent } from "@/lib/storefront/sector-design/config";
import { getDefaultTenantStorefrontSettings } from "@/lib/data";
import { demoTenants, demoProducts } from "@/lib/demo-data";
import type { StorefrontProduct } from "@/lib/types";
export const metadata = { title: "Elektrik ve aydınlatma tema incelemesi", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";
export default async function ElectricityReview({ searchParams }: { searchParams: Promise<{ tema?: string }> }) {
  if (process.env.NODE_ENV !== "development") notFound();
  const { tema } = await searchParams;
  const tenant = { ...demoTenants[0], id: "theme-review-electricity", subdomain: "theme-review-electricity", company_name: "IŞIK ELEKTRİK", sector: "elektrik", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Elektrik malzemeleri ve aydınlatma ürünleri", is_hero_visible: false, is_theme_toggle_visible: true };
  // Existing catalog photography; prices and inventory below are local demo data.
  const samples = [{"name": "Panasonic Led Ampul E27 10.5W 1055Lm 4000K", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/39109136.jpg", "category": "bulbs", "price": 89}, {"name": "USB LED MASA LAMBASI", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/2500000104459.jpg", "category": "lamps", "price": 349}, {"name": "Viko Multi-let Siyah Üçlü Priz Topraklı Kablolu 2 M", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/39109230.jpg", "category": "sockets", "price": 279}, {"name": "Nilson Akım Korumalı Beyaz Tekli Fiş Priz", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/39149238.jpg", "category": "protection", "price": 189}, {"name": "Philips Led Ampul 8W E27 6500K Beyaz Işık", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/39100141.jpg", "category": "bulbs", "price": 99}, {"name": "KATLANABİLİR LED MASA LAMBASI", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/6912000242660.jpg", "category": "lamps", "price": 449}, {"name": "Nilson 4'lü Topraklı Anahtarlı Grup Priz 5 Mt Kablo", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/39149233.jpg", "category": "sockets", "price": 399}, {"name": "Fulltech Termal Akım Korumalı Tekli Priz 3xusb", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8681830012405.jpg", "category": "protection", "price": 299}, {"name": "Kodak Led Ampul 9W RGB Kumandalı", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8684641680085.jpg", "category": "bulbs", "price": 199}, {"name": "Led Lityum Koruma Gözlü Masa Lambası", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/6931709041961.jpg", "category": "lamps", "price": 549}, {"name": "Viko Yonca Plus Beyaz Üçlü Topraklı Priz", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/39140012.jpg", "category": "sockets", "price": 159}, {"name": "Nilson Akım Korumalı Beyaz Usbli Fiş Priz", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/39149239.jpg", "category": "protection", "price": 249}];
  const products: StorefrontProduct[] = samples.map((x,i)=>({...demoProducts[0],id:`electricity-sample-${i}`,category_id:x.category,sku_code:`ELK-${1000+i}`,product_name:x.name,image_url:x.image,image_url_2:null,image_url_3:null,price:x.price,package_quantity:6,carton_quantity:24,stock_quantity:120,is_in_stock:true,has_variants:false,variants:[],volume_pricing:null}));
  const categories=[{"id": "bulbs", "name": "LED Ampuller"}, {"id": "lamps", "name": "Masa Lambaları"}, {"id": "sockets", "name": "Grup Prizler"}, {"id": "protection", "name": "Akım Koruma"}].map((c,i)=>({...c,tenant_id:tenant.id,parent_id:null,banner_item:null,tile_image_url:null,is_discount_category:false,is_hidden_from_storefront:false,display_order:i,created_at:"2026-01-01T00:00:00Z"}));
  return <ElectronicsReview tenant={tenant} products={products} categories={categories} settings={settings} contentOverrides={{"electricity-lumen":{...defaultContent("electricity-lumen"),heroCategoryId:"bulbs",collectionCategoryId:"lamps"},"electricity-volt":{...defaultContent("electricity-volt"),promoCategoryId:"bulbs",secondCategoryId:"protection"}}} initialTheme={isDesignId(tema) && tema.startsWith("electricity-")?tema:"electricity-lumen"}/>;
}
