import { notFound } from "next/navigation";
import { ElectronicsReview } from "@/components/storefront/sector-design/electronics-review";
import { isDesignId, defaultContent } from "@/lib/storefront/sector-design/config";
import { getDefaultTenantStorefrontSettings } from "@/lib/data";
import { demoTenants, demoProducts } from "@/lib/demo-data";
import type { StorefrontProduct } from "@/lib/types";
export const metadata = { title: "Ev, mutfak ve züccaciye tema incelemesi", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";
export default async function HomewareReview({ searchParams }: { searchParams: Promise<{ tema?: string }> }) {
  if (process.env.NODE_ENV !== "development") notFound();
  const { tema } = await searchParams;
  const tenant = { ...demoTenants[0], id: "theme-review-homeware", subdomain: "theme-review-homeware", company_name: "EV & SOFRA", sector: "ev-mutfak", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Ev, mutfak ve züccaciye ürünleri", is_hero_visible: false, is_theme_toggle_visible: true };
  // Existing catalog photography; prices and inventory below are local demo data.
  const samples = [{"name": "Keramika Aura Kupa 9 Cm", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/33058884.jpg", "category": "cups", "price": 149}, {"name": "Keramika Marin Servis Tabak 26 Cm", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/33058027.jpg", "category": "table", "price": 249}, {"name": "Mien Bubble Seramik Vazo 21 cm", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8684180921434.jpg", "category": "decor", "price": 399}, {"name": "Tefal Titanyum 2X XL Force Tava 24 Cm", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/32020442.jpg", "category": "cooking", "price": 899}, {"name": "Lav Fresco Saklama Kabı 1150 Cc", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/33030542.jpg", "category": "storage", "price": 189}, {"name": "Paşabahçe Aida Çay Bardağı 6'lı", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/33010014.jpg", "category": "glass", "price": 299}, {"name": "Touch Me Akasya Kase 16X7 Cm", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/32120286.jpg", "category": "table", "price": 349}, {"name": "Touch Me New Bone Soft Kupa 370 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/33054749.jpg", "category": "cups", "price": 129}, {"name": "Paşabahçe Lavinia Crystallin Vazo", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/40310315.jpg", "category": "decor", "price": 449}, {"name": "Papilla Ragnar Wok Tava 28 Cm", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/32020501.jpg", "category": "cooking", "price": 599}, {"name": "Qlux Ideas Bomonti Saklama Kabı Set No:1 4 x 700 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/32088225.jpg", "category": "storage", "price": 229}, {"name": "Paşabahçe Timeless Fincan / Kupa 2'li 315 Cc", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/33030913.jpg", "category": "glass", "price": 349}];
  const products: StorefrontProduct[] = samples.map((x,i)=>({...demoProducts[0],id:`homeware-sample-${i}`,category_id:x.category,sku_code:`EV-${1000+i}`,product_name:x.name,image_url:x.image,image_url_2:null,image_url_3:null,price:x.price,package_quantity:6,carton_quantity:24,stock_quantity:120,is_in_stock:true,has_variants:false,variants:[],volume_pricing:null}));
  const categories=[{"id": "table", "name": "Sofra & Sunum"}, {"id": "cups", "name": "Kupa & Fincan"}, {"id": "glass", "name": "Cam & Bardak"}, {"id": "cooking", "name": "Pişirme"}, {"id": "storage", "name": "Saklama & Düzen"}, {"id": "decor", "name": "Ev Dekorasyonu"}].map((c,i)=>({...c,tenant_id:tenant.id,parent_id:null,banner_item:null,tile_image_url:null,is_discount_category:false,is_hidden_from_storefront:false,display_order:i,created_at:"2026-01-01T00:00:00Z"}));
  return <ElectronicsReview tenant={tenant} products={products} categories={categories} settings={settings} contentOverrides={{"homeware-yuva":{...defaultContent("homeware-yuva"),heroCategoryId:"all",collectionCategoryId:"table"},"homeware-sofra":{...defaultContent("homeware-sofra"),promoCategoryId:"cups",secondCategoryId:"storage"}}} initialTheme={isDesignId(tema) && tema.startsWith("homeware-")?tema:"homeware-yuva"}/>;
}
