// Otomatik üretildi (11-12 Ağu 2026) — her ürün adı/açıklamasından Gemini ile
// sınıflandırılıp 21 sabit ana kategoriye ve konsolide edilmiş alt kategorilere
// atandı, ardından birkaç alt kategori elle taşındı/yeniden adlandırıldı (aynı
// yaprak isminin iki farklı ana kategoride kullanılmasını önlemek için — örn.
// "Kahve" hem Kahvaltılık hem Su & İçecek altında çıkmıştı, ikincisi "Hazır Kahve
// İçeceği" oldu). Anahtar, market_catalog_products.category_name'de saklanan
// yaprak (en spesifik) alt kategori adı; değer tek elemanlı bir ata zinciri (şu an
// tüm ağaç iki seviyeli: ana kategori → alt kategori). Haritada olmayan bir isim
// kök seviyede kalır (tek elemanlı yol).
export const MARKET_CATEGORY_ANCESTORS: Record<string, string[]> = {
  "Atıştırmalık & Tatlı": ["Temel Gıda"],
  "Atıştırmalık Bar": ["Atıştırmalık"],
  "Atıştırmalık ve Bisküvi": ["Kahvaltılık"],
  "Atıştırmalık ve Diğer": ["Dondurulmuş"],
  "Ayakkabı & Terlik": ["Ev & Yaşam"],
  "Aydınlatma & Mum": ["Ev & Yaşam"],
  "Aydınlatma ve Ampul": ["Teknoloji"],
  "Ağız ve Diş Sağlığı": ["Kişisel Bakım"],
  "Baharatlar": ["Temel Gıda"],
  "Bahçe & Çiçek": ["Ev & Yaşam"],
  "Bakliyat & Pirinç": ["Temel Gıda"],
  "Balık & Konserve": ["Et, Tavuk & Balık"],
  "Banyo Aksesuarları": ["Ev & Yaşam"],
  "Banyo ve Tuvalet Temizliği": ["Ev Bakım"],
  "Bebek Araç ve Gereçleri": ["Bebek"],
  "Bebek Bakım ve Temizlik": ["Bebek"],
  "Bebek Bezi ve Islak Mendil": ["Bebek"],
  "Bebek Giyim ve Aksesuar": ["Bebek"],
  "Bebek Maması ve Ek Gıda": ["Bebek"],
  "Bebek Sütü ve İçecekler": ["Bebek"],
  "Biberon ve Emzik": ["Bebek"],
  "Bira": ["Alkol"],
  "Bisküvi": ["Atıştırmalık"],
  "Bitki Çayı": ["Su & İçecek"],
  "Bulaşık Yıkama Ürünleri": ["Ev Bakım"],
  "Börek ve Hamur İşleri": ["Fırından"],
  "Cider ve Sidre": ["Alkol"],
  "Cilt Bakımı": ["Kişisel Bakım"],
  "Cin": ["Alkol"],
  "Cips": ["Atıştırmalık"],
  "Deniz & Havuz": ["Ev & Yaşam"],
  "Deodorant ve Vücut Spreyi": ["Kişisel Bakım"],
  "Diyet ve Sağlıklı Gıda Ürünleri": ["Fit & Form"],
  "Diğer Alkollü İçecekler": ["Alkol"],
  "Diğer Ev Bakım Ürünleri": ["Ev Bakım"],
  "Diğer Evcil Hayvan Ürünleri": ["Evcil Hayvan"],
  "Diğer Meyve & Sebze": ["Meyve & Sebze"],
  "Diğer Süt Ürünleri": ["Süt Ürünleri"],
  "Diğer Ürünler": ["Su & İçecek"],
  "Dondurma": ["Dondurma"],
  "Dondurma Malzemeleri ve Aksesuarları": ["Dondurma"],
  "Dondurulmuş Börek ve Hamur İşleri": ["Dondurulmuş"],
  "Dondurulmuş Meyve": ["Dondurulmuş"],
  "Dondurulmuş Patates ve Kızartmalıklar": ["Dondurulmuş"],
  "Dondurulmuş Sebze": ["Dondurulmuş"],
  "Dondurulmuş Tatlı ve Pasta": ["Dondurulmuş"],
  "Duş ve Banyo": ["Kişisel Bakım"],
  "Ekmek ve Unlu Mamuller": ["Fırından"],
  "El Aletleri ve Hırdavat": ["Teknoloji"],
  "El, Ayak ve Vücut Bakımı": ["Kişisel Bakım"],
  "Elektrik ve Kablolama": ["Teknoloji"],
  "Enerji & Spor İçeceği": ["Su & İçecek"],
  "Et": ["Et, Tavuk & Balık"],
  "Ev Dekorasyon": ["Ev & Yaşam"],
  "Ev Gereçleri ve Aksesuarlar": ["Ev Bakım"],
  "Ev Tekstili": ["Ev & Yaşam"],
  "Ev ve Yaşam": ["Teknoloji"],
  "Evcil Hayvan Aksesuarları": ["Evcil Hayvan"],
  "Evcil Hayvan Bakım ve Kozmetik": ["Evcil Hayvan"],
  "Fotoğraf ve Baskı": ["Teknoloji"],
  "Fındık Ezmeli Lokma": ["Atıştırmalık"],
  "Fındık Ezmesi & Kreması": ["Atıştırmalık"],
  "Gazlı İçecek": ["Su & İçecek"],
  "Geleneksel & Diğer İçecekler": ["Su & İçecek"],
  "Geleneksel Tatlılar": ["Atıştırmalık"],
  "Giyim": ["Ev & Yaşam"],
  "Gofret": ["Atıştırmalık"],
  "Granola": ["Atıştırmalık"],
  "Güneş Ürünleri": ["Kişisel Bakım"],
  "Hamur İşi ve Mantı": ["Pratik Yemek"],
  "Hava Kokulandırıcılar": ["Ev Bakım"],
  "Hazır Kahve İçeceği": ["Su & İçecek"],
  "Hazır Yemek": ["Pratik Yemek"],
  "Hazır Yemek & Diğer": ["Temel Gıda"],
  "Hazır Yemek ve Yemeklikler": ["Dondurulmuş"],
  "Hazır Çay İçeceği": ["Su & İçecek"],
  "Haşere ve Böcek İlaçları": ["Ev Bakım"],
  "Helva": ["Atıştırmalık"],
  "Hijyenik Ped ve Kadın Sağlığı": ["Kişisel Bakım"],
  "Hırdavat & Oto": ["Ev & Yaşam"],
  "Kahvaltılık Ezme & Kremalar": ["Temel Gıda"],
  "Kahvaltılık Gevrek ve Granola": ["Kahvaltılık"],
  "Kahvaltılık Sos ve Diğer": ["Kahvaltılık"],
  "Kahvaltılık ve Tahıllar": ["Fit & Form"],
  "Kahve": ["Kahvaltılık"],
  "Kahve & Çay": ["Temel Gıda"],
  "Kamp & Piknik": ["Ev & Yaşam"],
  "Kayganlaştırıcı ve Masaj Jelleri": ["Cinsel Sağlık"],
  "Kağıt Ürünleri ve Islak Mendil": ["Ev Bakım"],
  "Kedi Kumu ve Tuvalet İhtiyaçları": ["Evcil Hayvan"],
  "Kedi Maması ve Konservesi": ["Evcil Hayvan"],
  "Kedi Ödülleri ve Çorbaları": ["Evcil Hayvan"],
  "Kefir ve Ayran": ["Süt Ürünleri"],
  "Kek": ["Atıştırmalık"],
  "Kişisel Bakım Aksesuarları": ["Kişisel Bakım"],
  "Kişisel Bakım Aletleri": ["Teknoloji"],
  "Kokteyl ve Aperitif": ["Alkol"],
  "Konserve": ["Pratik Yemek"],
  "Konyak ve Brandy": ["Alkol"],
  "Kraker": ["Atıştırmalık"],
  "Krem Peynir ve Sürülebilir Ürünler": ["Süt Ürünleri"],
  "Krema ve Margarin": ["Süt Ürünleri"],
  "Kurabiye": ["Atıştırmalık"],
  "Kurabiye ve Bisküvi": ["Atıştırmalık"],
  "Kuru Meyve": ["Atıştırmalık"],
  "Kuru Meyve & Kuruyemiş": ["Atıştırmalık"],
  "Kuruyemiş": ["Atıştırmalık"],
  "Kutu Dondurma": ["Dondurma"],
  "Kuş ve Kemirgen Yemleri": ["Evcil Hayvan"],
  "Köpek Maması ve Konservesi": ["Evcil Hayvan"],
  "Köpek Ödülleri ve Bisküvileri": ["Evcil Hayvan"],
  "Külahlı Dondurma": ["Dondurma"],
  "Kırtasiye & Parti": ["Ev & Yaşam"],
  "Likör": ["Alkol"],
  "Lokum": ["Atıştırmalık"],
  "Maden Suyu & Soda": ["Su & İçecek"],
  "Makarna & Şehriye": ["Temel Gıda"],
  "Makarna ve Noodle": ["Pratik Yemek"],
  "Makyaj": ["Kişisel Bakım"],
  "Maraş ve Kesme Dondurma": ["Dondurma"],
  "Meyve": ["Meyve & Sebze"],
  "Meyve Suyu & Nektarı": ["Su & İçecek"],
  "Meze": ["Pratik Yemek"],
  "Meze ve Salata": ["Pratik Yemek"],
  "Mutfak Gereçleri": ["Ev & Yaşam"],
  "Oto ve Araç Bakım": ["Ev Bakım"],
  "Oto ve Bisiklet Aksesuarları": ["Teknoloji"],
  "Oyuncak ve Eğlence": ["Teknoloji"],
  "Parfüm ve Kolonya": ["Kişisel Bakım"],
  "Pasta Malzemeleri": ["Temel Gıda"],
  "Pasta ve Kek": ["Fırından"],
  "Patlamış Mısır": ["Atıştırmalık"],
  "Peynir": ["Süt Ürünleri"],
  "Pil ve Güç Kaynakları": ["Teknoloji"],
  "Pizza ve Pide": ["Dondurulmuş"],
  "Prezervatif ve Kondom": ["Cinsel Sağlık"],
  "Protein ve Sporcu Gıdaları": ["Fit & Form"],
  "Puding & Tatlı": ["Atıştırmalık"],
  "Rakı": ["Alkol"],
  "Reçel, Bal ve Ezme": ["Kahvaltılık"],
  "Rom": ["Alkol"],
  "Sabun ve Kişisel Temizlik": ["Ev Bakım"],
  "Sabun ve Sıvı Sabun": ["Kişisel Bakım"],
  "Sakız": ["Atıştırmalık"],
  "Salça": ["Temel Gıda"],
  "Sandviç Dondurma": ["Dondurma"],
  "Sandviç ve Fast Food": ["Pratik Yemek"],
  "Saç Bakım ve Şekillendirme": ["Kişisel Bakım"],
  "Sağlık ve İlk Yardım": ["Kişisel Bakım"],
  "Sağlıklı Atıştırmalıklar ve Barlar": ["Fit & Form"],
  "Sebze": ["Meyve & Sebze"],
  "Sigara Aksesuarları ve Gereçleri": ["Sigara"],
  "Sigara ve Tütün Ürünleri": ["Sigara"],
  "Sirke & Nar Ekşisi": ["Temel Gıda"],
  "Sofra & Servis": ["Ev & Yaşam"],
  "Sorbe ve Meyveli Dondurma": ["Dondurma"],
  "Sos": ["Pratik Yemek"],
  "Soslar": ["Temel Gıda"],
  "Soğuk Kahve": ["Su & İçecek"],
  "Soğuk Çay": ["Su & İçecek"],
  "Soğuk İçecek & Meşrubat": ["Su & İçecek"],
  "Spor Malzemeleri": ["Ev & Yaşam"],
  "Spor ve Outdoor": ["Teknoloji"],
  "Su": ["Su & İçecek"],
  "Sushi ve Asya Mutfağı": ["Pratik Yemek"],
  "Sürülebilir Çikolata ve Helva": ["Kahvaltılık"],
  "Süt": ["Süt Ürünleri"],
  "Süt ve Bitkisel Süt": ["Su & İçecek"],
  "Süt, Tereyağı ve Kaymak": ["Kahvaltılık"],
  "Sütlü Tatlılar": ["Süt Ürünleri"],
  "Sıvı Yağlar": ["Temel Gıda"],
  "Tatlı ve Tatlı Sosları": ["Pratik Yemek"],
  "Tavuk": ["Et, Tavuk & Balık"],
  "Tekila ve Mezcal": ["Alkol"],
  "Telefon Aksesuarları": ["Teknoloji"],
  "Temizlik & Düzen": ["Ev & Yaşam"],
  "Temizlik Aksesuarları ve Ekipmanları": ["Ev Bakım"],
  "Tereyağı ve Kaymak": ["Süt Ürünleri"],
  "Turşu & Konserve": ["Temel Gıda"],
  "Tuz": ["Temel Gıda"],
  "Tıraş ve Epilasyon": ["Kişisel Bakım"],
  "Tırnak Bakımı ve Oje": ["Kişisel Bakım"],
  "Un & Nişasta": ["Temel Gıda"],
  "Viski": ["Alkol"],
  "Vitamin ve Takviye Edici Gıdalar": ["Fit & Form"],
  "Votka": ["Alkol"],
  "Yaz ve Plaj Ürünleri": ["Bebek"],
  "Yetişkin ve Hasta Bakım": ["Bebek"],
  "Yeşillik & Otlar": ["Meyve & Sebze"],
  "Yoğurt": ["Süt Ürünleri"],
  "Yumurta": ["Kahvaltılık"],
  "Yumuşak Şeker": ["Atıştırmalık"],
  "Yüzey ve Genel Temizlik": ["Ev Bakım"],
  "Zeytin": ["Meyve & Sebze"],
  "Zeytin ve Meze": ["Kahvaltılık"],
  "Çakmak": ["Sigara"],
  "Çamaşır Yıkama Ürünleri": ["Ev Bakım"],
  "Çanta & Valiz": ["Ev & Yaşam"],
  "Çay": ["Kahvaltılık"],
  "Çikolata": ["Atıştırmalık"],
  "Çocuk Ağız ve Diş Sağlığı": ["Bebek"],
  "Çoklu ve Mini Dondurma": ["Dondurma"],
  "Çorba": ["Pratik Yemek"],
  "Çorba & Bulyon": ["Temel Gıda"],
  "Çubuk Dondurma": ["Dondurma"],
  "Çöp Torbaları ve Saklama Ürünleri": ["Ev Bakım"],
  "Özel ve Gurme Dondurma": ["Dondurma"],
  "İç Giyim": ["Ev & Yaşam"],
  "İç Giyim ve Çorap": ["Kişisel Bakım"],
  "İçecekler ve Çaylar": ["Fit & Form"],
  "Şampanya ve Köpüklü Şarap": ["Alkol"],
  "Şarap": ["Alkol"],
  "Şarküteri & Hazır Et": ["Et, Tavuk & Balık"],
  "Şeker": ["Atıştırmalık"],
  "Şeker & Tatlandırıcılar": ["Temel Gıda"],
  "Şekerleme": ["Atıştırmalık"],
};

// Kök→yaprak sırayla tam yol. Haritada olmayan adlar tek elemanlı (kendi
// kendinin kökü) yol döner — gelecekte yeni bir alt kategori eklenirse kırılmadan
// düz kök olarak eklenir.
export function resolveCategoryPath(categoryName: string): string[] {
  const ancestors = MARKET_CATEGORY_ANCESTORS[categoryName] ?? [];
  return [...ancestors, categoryName];
}
