// Migros'un kategori breadcrumb'larından (json-kaydetme crawler) türetildi.
// Anahtar, market_catalog_products.category_name'de saklanan yaprak (en
// spesifik) kategori adı; değer kök→üst sırayla ata zinciri. Haritada
// olmayan bir kategori adı kök seviyede kalır (tek elemanlı yol).
export const MARKET_CATEGORY_ANCESTORS: Record<string, string[]> = {
  "Ahşap Temizleyiciler": ["Deterjan, Temizlik", "Genel Temizlik"],
  Askı: ["Deterjan, Temizlik", "Çamaşır Gereçleri"],
  Baharat: ["Temel Gıda", "Tuz, Baharat, Harç"],
  "Bahçe Mobilyası": ["Ev, Yaşam", "Mobilya, Dekorasyon"],
  "Bahçe ve Piknik Malzemeleri": ["Ev, Yaşam"],
  Bakliyat: ["Temel Gıda"],
  Bal: ["Süt, Kahvaltılık", "Kahvaltılıklar"],
  "Banyo Gereçleri": ["Deterjan, Temizlik"],
  "Banyo Plastikleri": ["Deterjan, Temizlik", "Banyo Gereçleri"],
  "Bar, Kaplamalılar": ["Atıştırmalık"],
  Bardak: ["Ev, Yaşam", "Mutfak Eşyaları"],
  "Beyaz Peynir": ["Süt, Kahvaltılık", "Peynir"],
  Bisküvi: ["Atıştırmalık"],
  "Bulaşık Makinesi Ürünleri": ["Deterjan, Temizlik", "Bulaşık Yıkama"],
  "Bulaşık Yıkama": ["Deterjan, Temizlik"],
  Bulgur: ["Temel Gıda", "Bakliyat"],
  Cips: ["Atıştırmalık"],
  "Çamaşır Deterjanı": ["Deterjan, Temizlik", "Çamaşır Yıkama"],
  "Çamaşır Gereçleri": ["Deterjan, Temizlik"],
  "Çamaşır Suyu": ["Deterjan, Temizlik", "Çamaşır Yıkama"],
  "Çamaşır Yıkama": ["Deterjan, Temizlik"],
  Çay: ["İçecek"],
  Çikolata: ["Atıştırmalık"],
  "Deniz, Havuz Ürünleri": ["Ev, Yaşam", "Spor, Outdoor"],
  "Dijital Kodlar, Kartlar": ["Ev, Yaşam"],
  "Ev Tekstili": ["Ev, Yaşam"],
  "Ev, Ofis Mobilyaları": ["Ev, Yaşam", "Mobilya, Dekorasyon"],
  "Fırında Pişirme": ["Ev, Yaşam", "Mutfak Eşyaları"],
  "Gazlı İçecek": ["İçecek"],
  "Gazsız İçecek": ["İçecek"],
  "Genel Temizlik": ["Deterjan, Temizlik"],
  Gofret: ["Atıştırmalık"],
  "Hamur, Pasta Malzemeleri": ["Temel Gıda"],
  "Haşere Öldürücüler": ["Deterjan, Temizlik", "Genel Temizlik"],
  "Hava Temizleyiciler": ["Deterjan, Temizlik", "Genel Temizlik"],
  "Helva, Tahin, Pekmez": ["Süt, Kahvaltılık", "Kahvaltılıklar"],
  Hırdavat: ["Ev, Yaşam"],
  "Kağıt Havlu": ["Kağıt, Islak Mendil"],
  "Kahvaltılık Gevrek": ["Süt, Kahvaltılık", "Kahvaltılıklar"],
  Kahvaltılıklar: ["Süt, Kahvaltılık"],
  Kahve: ["İçecek"],
  "Kamp Malzemeleri": ["Ev, Yaşam", "Spor, Outdoor"],
  "Kaşar Peyniri": ["Süt, Kahvaltılık", "Peynir"],
  Kek: ["Atıştırmalık"],
  Konserve: ["Temel Gıda"],
  "Krem Çikolata, Ezmeler": ["Süt, Kahvaltılık", "Kahvaltılıklar"],
  "Kuru Meyve": ["Atıştırmalık"],
  "Kuru Pasta": ["Fırın, Pastane"],
  Kuruyemiş: ["Atıştırmalık"],
  "Leke Çıkarıcı ve Koruyucular": ["Deterjan, Temizlik", "Genel Temizlik"],
  Makarnalar: ["Temel Gıda"],
  "Mangal, Barbekü": ["Ev, Yaşam", "Bahçe ve Piknik Malzemeleri"],
  Margarin: ["Süt, Kahvaltılık"],
  Mercimek: ["Temel Gıda", "Bakliyat"],
  Meyve: ["Meyve, Sebze"],
  "Mobilya, Dekorasyon": ["Ev, Yaşam"],
  "Moda, Tekstil": ["Ev, Yaşam"],
  "Mum ve Mumluk": ["Ev, Yaşam", "Mobilya, Dekorasyon"],
  "Mutfak Eşyaları": ["Ev, Yaşam"],
  "Mutfak Sarf Malzemesi": ["Ev, Yaşam", "Mutfak Eşyaları"],
  "Oto Aksesuar": ["Ev, Yaşam"],
  "Parti Malzemeleri": ["Ev, Yaşam", "Mobilya, Dekorasyon"],
  Peynir: ["Süt, Kahvaltılık"],
  Pirinç: ["Temel Gıda", "Bakliyat"],
  Pişirme: ["Ev, Yaşam", "Mutfak Eşyaları"],
  "Plaj Giyim": ["Ev, Yaşam", "Moda, Tekstil"],
  "Reçel, Marmelat": ["Süt, Kahvaltılık", "Kahvaltılıklar"],
  "Renk Koruyucular": ["Deterjan, Temizlik", "Çamaşır Yıkama"],
  "Saklama, Düzenleme": ["Ev, Yaşam", "Mutfak Eşyaları"],
  Salça: ["Temel Gıda", "Konserve"],
  "Servis, Sunum": ["Ev, Yaşam", "Mutfak Eşyaları"],
  "Sıvı Yağ": ["Temel Gıda"],
  Sos: ["Temel Gıda"],
  "Spor Malzemeleri": ["Ev, Yaşam", "Spor, Outdoor"],
  "Spor, Outdoor": ["Ev, Yaşam"],
  "Süper Gıdalar": ["Temel Gıda", "Bakliyat"],
  Süt: ["Süt, Kahvaltılık"],
  "Sütlü Tatlı, Krema": ["Süt, Kahvaltılık"],
  "Sütlü Tatlılar": ["Süt, Kahvaltılık", "Sütlü Tatlı, Krema"],
  Şeker: ["Temel Gıda"],
  Şekerleme: ["Atıştırmalık"],
  "Temizlik Bezi": ["Deterjan, Temizlik", "Temizlik Malzemeleri"],
  "Temizlik Malzemeleri": ["Deterjan, Temizlik"],
  "Temizlik Süngeri": ["Deterjan, Temizlik", "Temizlik Malzemeleri"],
  Turşu: ["Temel Gıda", "Konserve"],
  "Tuvalet Temizleyiciler": ["Deterjan, Temizlik", "Genel Temizlik"],
  "Tuz, Baharat, Harç": ["Temel Gıda"],
  Un: ["Temel Gıda"],
  "Yatak Tekstili": ["Ev, Yaşam", "Ev Tekstili"],
  "Yemek Hazırlama": ["Ev, Yaşam", "Mutfak Eşyaları"],
  "Yeşil Zeytin": ["Süt, Kahvaltılık", "Zeytin"],
  "Yılbaşı Malzemeleri": ["Ev, Yaşam", "Mobilya, Dekorasyon"],
  Yoğurt: ["Süt, Kahvaltılık"],
  Yumuşatıcı: ["Deterjan, Temizlik", "Çamaşır Yıkama"],
  "Yüzey Temizleyiciler": ["Deterjan, Temizlik", "Genel Temizlik"],
  Zeytin: ["Süt, Kahvaltılık"],
  "Zeytin Ezmesi": ["Süt, Kahvaltılık", "Zeytin"],
  Zeytinyağı: ["Temel Gıda", "Sıvı Yağ"],
};

// Kök→yaprak sırayla tam yol. Haritada olmayan adlar tek elemanlı (kendi
// kendinin kökü) yol döner — gelecekte crawler yeni bir üst kategori
// eklerse kırılmadan düz kök olarak eklenir.
export function resolveCategoryPath(categoryName: string): string[] {
  const ancestors = MARKET_CATEGORY_ANCESTORS[categoryName] ?? [];
  return [...ancestors, categoryName];
}
