// Otomatik üretildi (11-12 Ağu 2026) — her ürün adı/açıklamasından Gemini ile
// sınıflandırılıp 21 sabit ana kategoriye ve konsolide edilmiş alt kategorilere
// atandı, ardından birkaç alt kategori elle taşındı/yeniden adlandırıldı (aynı
// yaprak isminin iki farklı ana kategoride kullanılmasını önlemek için — örn.
// "Kahve" hem Kahvaltılık hem Su & İçecek altında çıkmıştı, ikincisi "Hazır Kahve
// İçeceği" oldu). Anahtar, market_catalog_products.category_name'de saklanan
// yaprak (en spesifik) alt kategori adı; değer tek elemanlı bir ata zinciri (şu an
// tüm ağaç iki seviyeli: ana kategori → alt kategori). Haritada olmayan bir isim
// kök seviyede kalır (tek elemanlı yol).
export const MARKET_CATEGORY_ANCESTORS: Record<string, string[]> = {
  "Atıştırmalık & Tatlı": ["Atıştırmalık"],
  "Atıştırmalık Bar": ["Atıştırmalık"],
  "Atıştırmalık ve Bisküvi": ["Kahvaltılık"],
  "Atıştırmalık ve Diğer": ["Dondurulmuş"],
  "Ayakkabı & Terlik": ["Ev & Yaşam"],
  "Aydınlatma & Mum": ["Ev & Yaşam"],
  "Aydınlatma ve Ampul": ["Teknoloji"],
  "Ağız ve Diş Sağlığı": ["Kişisel Bakım"],
  "Baharatlar": ["Temel Gıda"],
  "Bahçe & Çiçek": ["Ev & Yaşam"],
  "Bakliyat & Pirinç": ["Temel Gıda"],
  "Balık & Konserve": ["Et, Tavuk & Balık"],
  "Banyo Aksesuarları": ["Ev & Yaşam"],
  "Banyo ve Tuvalet Temizliği": ["Ev Bakım"],
  "Bebek Araç ve Gereçleri": ["Bebek"],
  "Bebek Bakım ve Temizlik": ["Bebek"],
  "Bebek Bezi ve Islak Mendil": ["Bebek"],
  "Bebek Giyim ve Aksesuar": ["Bebek"],
  "Bebek Maması ve Ek Gıda": ["Bebek"],
  "Bebek Sütü ve İçecekler": ["Bebek"],
  "Biberon ve Emzik": ["Bebek"],
  "Bira": ["Alkol"],
  "Bisküvi": ["Atıştırmalık"],
  "Bitki Çayı": ["Su & İçecek"],
  "Bulaşık Yıkama Ürünleri": ["Ev Bakım"],
  "Börek ve Hamur İşleri": ["Fırından"],
  "Cider ve Sidre": ["Alkol"],
  "Cilt Bakımı": ["Kişisel Bakım"],
  "Cin": ["Alkol"],
  "Cips": ["Atıştırmalık"],
  "Deniz & Havuz": ["Ev & Yaşam"],
  "Deodorant ve Vücut Spreyi": ["Kişisel Bakım"],
  "Diyet ve Sağlıklı Gıda Ürünleri": ["Fit & Form"],
  "Diğer Alkollü İçecekler": ["Alkol"],
  "Diğer Ev Bakım Ürünleri": ["Ev Bakım"],
  "Diğer Evcil Hayvan Ürünleri": ["Evcil Hayvan"],
  "Diğer Meyve & Sebze": ["Meyve & Sebze"],
  "Diğer Süt Ürünleri": ["Süt Ürünleri"],
  "Diğer Ürünler": ["Su & İçecek"],
  "Dondurma Malzemeleri ve Aksesuarları": ["Dondurma"],
  "Dondurulmuş Börek ve Hamur İşleri": ["Dondurulmuş"],
  "Dondurulmuş Meyve": ["Dondurulmuş"],
  "Dondurulmuş Patates ve Kızartmalıklar": ["Dondurulmuş"],
  "Dondurulmuş Sebze": ["Dondurulmuş"],
  "Dondurulmuş Tatlı ve Pasta": ["Dondurulmuş"],
  "Duş ve Banyo": ["Kişisel Bakım"],
  "Ekmek ve Unlu Mamuller": ["Fırından"],
  "El Aletleri ve Hırdavat": ["Ev & Yaşam"],
  "El, Ayak ve Vücut Bakımı": ["Kişisel Bakım"],
  "Elektrik ve Kablolama": ["Teknoloji"],
  "Enerji & Spor İçeceği": ["Su & İçecek"],
  "Et": ["Et, Tavuk & Balık"],
  "Ev Dekorasyon": ["Ev & Yaşam"],
  "Ev Gereçleri ve Aksesuarlar": ["Ev Bakım"],
  "Ev Tekstili": ["Ev & Yaşam"],
  "Ev ve Yaşam": ["Ev & Yaşam"],
  "Evcil Hayvan Aksesuarları": ["Evcil Hayvan"],
  "Evcil Hayvan Bakım ve Kozmetik": ["Evcil Hayvan"],
  "Fotoğraf ve Baskı": ["Teknoloji"],
  "Fındık Ezmeli Lokma": ["Atıştırmalık"],
  "Fındık Ezmesi & Kreması": ["Atıştırmalık"],
  "Gazlı İçecek": ["Su & İçecek"],
  "Geleneksel & Diğer İçecekler": ["Su & İçecek"],
  "Geleneksel Tatlılar": ["Atıştırmalık"],
  "Giyim": ["Ev & Yaşam"],
  "Gofret": ["Atıştırmalık"],
  "Granola": ["Atıştırmalık"],
  "Güneş Ürünleri": ["Kişisel Bakım"],
  "Hamur İşi ve Mantı": ["Pratik Yemek"],
  "Hava Kokulandırıcılar": ["Ev Bakım"],
  "Hazır Kahve İçeceği": ["Su & İçecek"],
  "Hazır Yemek": ["Pratik Yemek"],
  "Hazır Yemek & Diğer": ["Temel Gıda"],
  "Hazır Yemek ve Yemeklikler": ["Dondurulmuş"],
  "Hazır Çay İçeceği": ["Su & İçecek"],
  "Haşere ve Böcek İlaçları": ["Ev Bakım"],
  "Helva": ["Atıştırmalık"],
  "Hijyenik Ped ve Kadın Sağlığı": ["Kişisel Bakım"],
  "Hırdavat & Oto": ["Ev & Yaşam"],
  "Kahvaltılık Ezme & Kremalar": ["Kahvaltılık"],
  "Kahvaltılık Gevrek ve Granola": ["Kahvaltılık"],
  "Kahvaltılık Sos ve Diğer": ["Kahvaltılık"],
  "Kahvaltılık ve Tahıllar": ["Fit & Form"],
  "Kahve": ["Kahvaltılık"],
  "Kahve & Çay": ["Kahvaltılık"],
  "Kamp & Piknik": ["Ev & Yaşam"],
  "Kayganlaştırıcı ve Masaj Jelleri": ["Cinsel Sağlık"],
  "Kağıt Ürünleri ve Islak Mendil": ["Ev Bakım"],
  "Kedi Kumu ve Tuvalet İhtiyaçları": ["Evcil Hayvan"],
  "Kedi Maması ve Konservesi": ["Evcil Hayvan"],
  "Kedi Ödülleri ve Çorbaları": ["Evcil Hayvan"],
  "Kefir ve Ayran": ["Süt Ürünleri"],
  "Kek": ["Atıştırmalık"],
  "Kişisel Bakım Aksesuarları": ["Kişisel Bakım"],
  "Kişisel Bakım Aletleri": ["Teknoloji"],
  "Kokteyl ve Aperitif": ["Alkol"],
  "Konserve": ["Pratik Yemek"],
  "Konyak ve Brandy": ["Alkol"],
  "Kraker": ["Atıştırmalık"],
  "Krem Peynir ve Sürülebilir Ürünler": ["Süt Ürünleri"],
  "Krema ve Margarin": ["Süt Ürünleri"],
  "Kurabiye": ["Atıştırmalık"],
  "Kurabiye ve Bisküvi": ["Atıştırmalık"],
  "Kuru Meyve": ["Atıştırmalık"],
  "Kuru Meyve & Kuruyemiş": ["Atıştırmalık"],
  "Kuruyemiş": ["Atıştırmalık"],
  "Kutu Dondurma": ["Dondurma"],
  "Kuş ve Kemirgen Yemleri": ["Evcil Hayvan"],
  "Köpek Maması ve Konservesi": ["Evcil Hayvan"],
  "Köpek Ödülleri ve Bisküvileri": ["Evcil Hayvan"],
  "Külahlı Dondurma": ["Dondurma"],
  "Kırtasiye & Parti": ["Ev & Yaşam"],
  "Likör": ["Alkol"],
  "Lokum": ["Atıştırmalık"],
  "Maden Suyu & Soda": ["Su & İçecek"],
  "Makarna & Şehriye": ["Temel Gıda"],
  "Makarna ve Noodle": ["Pratik Yemek"],
  "Makyaj": ["Kişisel Bakım"],
  "Maraş ve Kesme Dondurma": ["Dondurma"],
  "Meyve": ["Meyve & Sebze"],
  "Meyve Suyu & Nektarı": ["Su & İçecek"],
  "Meze": ["Pratik Yemek"],
  "Meze ve Salata": ["Pratik Yemek"],
  "Mutfak Gereçleri": ["Ev & Yaşam"],
  "Oto ve Araç Bakım": ["Ev Bakım"],
  "Oto ve Bisiklet Aksesuarları": ["Ev & Yaşam"],
  "Oyuncak ve Eğlence": ["Ev & Yaşam"],
  "Parfüm ve Kolonya": ["Kişisel Bakım"],
  "Pasta Malzemeleri": ["Temel Gıda"],
  "Pasta ve Kek": ["Fırından"],
  "Patlamış Mısır": ["Atıştırmalık"],
  "Peynir": ["Süt Ürünleri"],
  "Pil ve Güç Kaynakları": ["Teknoloji"],
  "Pizza ve Pide": ["Dondurulmuş"],
  "Prezervatif ve Kondom": ["Cinsel Sağlık"],
  "Protein ve Sporcu Gıdaları": ["Fit & Form"],
  "Puding & Tatlı": ["Atıştırmalık"],
  "Rakı": ["Alkol"],
  "Reçel, Bal ve Ezme": ["Kahvaltılık"],
  "Rom": ["Alkol"],
  "Sabun ve Kişisel Temizlik": ["Ev Bakım"],
  "Sabun ve Sıvı Sabun": ["Kişisel Bakım"],
  "Sakız": ["Atıştırmalık"],
  "Salça": ["Temel Gıda"],
  "Sandviç Dondurma": ["Dondurma"],
  "Sandviç ve Fast Food": ["Pratik Yemek"],
  "Saç Bakım ve Şekillendirme": ["Kişisel Bakım"],
  "Sağlık ve İlk Yardım": ["Kişisel Bakım"],
  "Sağlıklı Atıştırmalıklar ve Barlar": ["Fit & Form"],
  "Sebze": ["Meyve & Sebze"],
  "Sigara Aksesuarları ve Gereçleri": ["Sigara"],
  "Sigara ve Tütün Ürünleri": ["Sigara"],
  "Sirke & Nar Ekşisi": ["Temel Gıda"],
  "Sofra & Servis": ["Ev & Yaşam"],
  "Sorbe ve Meyveli Dondurma": ["Dondurma"],
  "Sos": ["Pratik Yemek"],
  "Soslar": ["Temel Gıda"],
  "Soğuk Kahve": ["Su & İçecek"],
  "Soğuk Çay": ["Su & İçecek"],
  "Soğuk İçecek & Meşrubat": ["Su & İçecek"],
  "Spor Malzemeleri": ["Ev & Yaşam"],
  "Spor ve Outdoor": ["Ev & Yaşam"],
  "Su": ["Su & İçecek"],
  "Sushi ve Asya Mutfağı": ["Pratik Yemek"],
  "Sürülebilir Çikolata ve Helva": ["Kahvaltılık"],
  "Süt": ["Süt Ürünleri"],
  "Süt ve Bitkisel Süt": ["Su & İçecek"],
  "Süt, Tereyağı ve Kaymak": ["Kahvaltılık"],
  "Sütlü Tatlılar": ["Süt Ürünleri"],
  "Sıvı Yağlar": ["Temel Gıda"],
  "Tatlı ve Tatlı Sosları": ["Pratik Yemek"],
  "Tavuk": ["Et, Tavuk & Balık"],
  "Tekila ve Mezcal": ["Alkol"],
  "Telefon Aksesuarları": ["Teknoloji"],
  "Temizlik & Düzen": ["Ev & Yaşam"],
  "Temizlik Aksesuarları ve Ekipmanları": ["Ev Bakım"],
  "Tereyağı ve Kaymak": ["Süt Ürünleri"],
  "Turşu & Konserve": ["Temel Gıda"],
  "Tuz": ["Temel Gıda"],
  "Tıraş ve Epilasyon": ["Kişisel Bakım"],
  "Tırnak Bakımı ve Oje": ["Kişisel Bakım"],
  "Un & Nişasta": ["Temel Gıda"],
  "Viski": ["Alkol"],
  "Vitamin ve Takviye Edici Gıdalar": ["Fit & Form"],
  "Votka": ["Alkol"],
  "Yaz ve Plaj Ürünleri": ["Bebek"],
  "Yetişkin ve Hasta Bakım": ["Bebek"],
  "Yeşillik & Otlar": ["Meyve & Sebze"],
  "Yoğurt": ["Süt Ürünleri"],
  "Yumurta": ["Kahvaltılık"],
  "Yumuşak Şeker": ["Atıştırmalık"],
  "Yüzey ve Genel Temizlik": ["Ev Bakım"],
  "Zeytin": ["Temel Gıda"],
  "Zeytin ve Meze": ["Kahvaltılık"],
  "Çakmak": ["Sigara"],
  "Çamaşır Yıkama Ürünleri": ["Ev Bakım"],
  "Çanta & Valiz": ["Ev & Yaşam"],
  "Çay": ["Kahvaltılık"],
  "Çikolata": ["Atıştırmalık"],
  "Çocuk Ağız ve Diş Sağlığı": ["Bebek"],
  "Çoklu ve Mini Dondurma": ["Dondurma"],
  "Çorba": ["Pratik Yemek"],
  "Çorba & Bulyon": ["Temel Gıda"],
  "Çubuk Dondurma": ["Dondurma"],
  "Çöp Torbaları ve Saklama Ürünleri": ["Ev Bakım"],
  "Özel ve Gurme Dondurma": ["Dondurma"],
  "İç Giyim": ["Ev & Yaşam"],
  "İç Giyim ve Çorap": ["Kişisel Bakım"],
  "İçecekler ve Çaylar": ["Fit & Form"],
  "Şampanya ve Köpüklü Şarap": ["Alkol"],
  "Şarap": ["Alkol"],
  "Şarküteri & Hazır Et": ["Et, Tavuk & Balık"],
  "Şeker": ["Atıştırmalık"],
  "Şeker & Tatlandırıcılar": ["Temel Gıda"],
  "Şekerleme": ["Atıştırmalık"],

  // 13-14 Ağustos 2026'da eklenen yeni Master Katalog kaynaklarından
  // (marketkarsilastir, asya_crawl, mopas_karsilastir,
  // bizim_market_karsilastir, sok_karsilastir) gelen kategori isimleri —
  // eklenmeden önce haritada yoktu, her biri kendi başına kopuk bir kök
  // kategori olarak duruyordu (ör. "İçecek" ile asıl kök "Su & İçecek"
  // birbirinden habersiz iki ayrı kategoriydi). "Kategorisiz" bilinçli
  // olarak haritaya eklenmedi — gerçekten kategorisi bilinmeyen ürünler
  // için dürüst bir köşe, yanlış bir kökle eşleştirmek daha kötü olurdu.
  "İçecek": ["Su & İçecek"],
  "Süt, Kahvaltılık": ["Kahvaltılık"],
  "Deterjan, Temizlik": ["Ev Bakım"],
  "Kişisel Bakım, Kozmetik": ["Kişisel Bakım"],
  "Ev, Yaşam": ["Ev & Yaşam"],

  // asya_crawl (ticimax tabanlı site) kategorileri
  "Ketçap Mayonez": ["Temel Gıda"],
  "Turşu Konserve Garnitür": ["Temel Gıda"],
  "PİŞİRME & SAKLAMA": ["Ev & Yaşam"],
  "Diş ve Ağız Bakımı": ["Kişisel Bakım"],
  "İÇECEKLER": ["Su & İçecek"],
  "Unlu Mamüller": ["Fırından"],
  "BİSKÜVİ-ÇİKOLATA": ["Atıştırmalık"],
  "Kefir Ayran ve Yoğurt": ["Süt Ürünleri"],
  "Margarin": ["Süt Ürünleri"],
  "Sirke Sos Şalgam": ["Temel Gıda"],
  "Beyaz Peynir": ["Süt Ürünleri"],
  "Köpek Ürünleri": ["Evcil Hayvan"],
  "ATIŞTIRMALIK": ["Atıştırmalık"],
  "Bisküvi ve Çikolata": ["Atıştırmalık"],
  "Bulaşık Deterjanı": ["Ev Bakım"],
  "Makarna": ["Temel Gıda"],
  "Kuş Ürünleri": ["Evcil Hayvan"],
  "Soğuk ve Sıcak İçeçekler": ["Su & İçecek"],
  "Pasta Tatlı Malzemeleri": ["Temel Gıda"],
  "Süzme Peynir": ["Süt Ürünleri"],
  "Sabun ve Duş Jeli": ["Kişisel Bakım"],
  "TEMİZLİK": ["Ev Bakım"],
  "Çocuk Atıştırmalıkları": ["Bebek"],
  "Su ve Soda": ["Su & İçecek"],
  "Deterjan": ["Ev Bakım"],
  "Kadınlara Özel": ["Kişisel Bakım"],
  "Bakliyat Pirinç Bulgur": ["Temel Gıda"],
  "Şerbetsiz Tatlılar": ["Atıştırmalık"],
  "SÜT ÜRÜNLERİ": ["Süt Ürünleri"],
  "ET ÜRÜNLERİ": ["Et, Tavuk & Balık"],
  "Peynir ve Zeytin": ["Süt Ürünleri"],
  "Baharat": ["Temel Gıda"],
  "Çerez Çeşitleri": ["Atıştırmalık"],
  "Tuvalet Kağıdı": ["Ev Bakım"],
  "Çay ve Kahve Çeşitleri": ["Kahvaltılık"],
  "Deterjan Yumuşatıcı": ["Ev Bakım"],
  "Kaşar ve Tost Peyniri": ["Süt Ürünleri"],
  "Gevrek": ["Atıştırmalık"],
  "Bal Reçel": ["Kahvaltılık"],
  "Yüzey Temizleyici": ["Ev Bakım"],
  "ŞEKER BAYRAMI": ["Atıştırmalık"],
  "Wee Emzik Biberon": ["Bebek"],
  "EKMEK": ["Fırından"],
  "Şampuan ve Saç Kremi": ["Kişisel Bakım"],
  "Meyveli Soda": ["Su & İçecek"],
  "UNTAD": ["Temel Gıda"],
  "Parfüm ve Deodorant": ["Kişisel Bakım"],
  "Helva Tahin Pekmez": ["Temel Gıda"],
  "Çamaşır Deterjanı": ["Ev Bakım"],
  "ÜLKER": ["Atıştırmalık"],
  "Minzi Lor ve Telli Peynir": ["Süt Ürünleri"],
  "Tuz ve Şeker": ["Temel Gıda"],
  "Mama": ["Bebek"],
  "Erkeklere Özel": ["Kişisel Bakım"],
  "Kefir": ["Süt Ürünleri"],
  "Meyve Suları": ["Su & İçecek"],
  "Dondurulmuş Gıda": ["Dondurulmuş"],
  "Sıvı Sabun": ["Kişisel Bakım"],
  "Çay Şeker": ["Kahvaltılık"],
  "Gazlı İçecekler": ["Su & İçecek"],
  "Kağıt Peçete Havlu": ["Ev Bakım"],
  "İKRAMLIKLAR": ["Atıştırmalık"],
  "Yumuşak Şekerleme": ["Atıştırmalık"],
  "Sabun Çeşitleri": ["Kişisel Bakım"],
  "KİŞİSEL BAKIM": ["Kişisel Bakım"],
  "Fındık Kreması": ["Atıştırmalık"],
  "Kuru Meyveler": ["Atıştırmalık"],
  "Kedi Ürünleri": ["Evcil Hayvan"],
  "Makine Temizliği": ["Ev Bakım"],
  "Sma": ["Bebek"],
  "Konserve Garnitür": ["Temel Gıda"],
  "Kek ve Kruvasan": ["Fırından"],
  "Diş Macunu": ["Kişisel Bakım"],
  "Çamaşır Suyu": ["Ev Bakım"],
  "Balık": ["Et, Tavuk & Balık"],
  "Islak Mendil ve Havlu": ["Ev Bakım"],
  "Probiyotik ve Meyveli Yoğurt": ["Süt Ürünleri"],
  "Yetişkin Hasta Bezi": ["Bebek"],
  "Şampuan": ["Kişisel Bakım"],
  "Helva Tahin ve Pekmez": ["Temel Gıda"],
  "Sucuk Salam Sosis Pastırma": ["Et, Tavuk & Balık"],
  "YÖRESEL": ["Temel Gıda"],
  "Bal": ["Kahvaltılık"],
  "Kullan-At Plastik": ["Ev Bakım"],
  "Şampuan ve Sabun": ["Kişisel Bakım"],
  "Çöp Torbası": ["Ev Bakım"],
  "Aptamil": ["Bebek"],
  "Sleepy": ["Bebek"],
  "Tereyağ": ["Süt Ürünleri"],
  "Krema Sos": ["Süt Ürünleri"],
  "UNO": ["Ev Bakım"],
  "Duru": ["Kişisel Bakım"],
  "Bakım Kremi ve Losyon": ["Kişisel Bakım"],
  "Head Shoulders": ["Kişisel Bakım"],
  "PETSHOP": ["Evcil Hayvan"],
  "Pamuklu Ürünler": ["Kişisel Bakım"],
  "Reçel": ["Kahvaltılık"],
  "Kadayıf & Güllaç": ["Fırından"],
  "Bebelac": ["Bebek"],
  "PİL": ["Teknoloji"],
  "SAKIZ": ["Atıştırmalık"],
  "ÇAY": ["Kahvaltılık"],
  "Çikolatalı Fındık Kreması": ["Atıştırmalık"],
  "Enerji İçecekleri": ["Su & İçecek"],
  "Borcam ve Cam Tepsi": ["Ev & Yaşam"],
  "ÇİKOLATA": ["Atıştırmalık"],
  "TEMEL GIDA": ["Temel Gıda"],
  "GIDA": ["Temel Gıda"],
  "KAMP & MANGAL": ["Ev & Yaşam"],
  "Labne ve Krem Peynir": ["Süt Ürünleri"],
  "CİPS & KURUYEMİŞ": ["Atıştırmalık"],
  "Bitkisel Çay Aroma Tatlandırıcı": ["Su & İçecek"],
  "Peçete": ["Ev Bakım"],
  "Lokmalık": ["Atıştırmalık"],
  "Süt ve Süt Ürünleri": ["Süt Ürünleri"],
  "ET Ürünleri": ["Et, Tavuk & Balık"],
  "Kağıt Ürünleri": ["Ev Bakım"],
  "MAE YUMURTA": ["Kahvaltılık"],
  "Clear": ["Kişisel Bakım"],
  "BabyTurco": ["Bebek"],
  "Elidor": ["Kişisel Bakım"],
  "Hipp": ["Bebek"],
  "Glutensiz Ürünler": ["Fit & Form"],
  "Pantene": ["Kişisel Bakım"],
  "Duş Jeli": ["Kişisel Bakım"],
  "Saç Kremi": ["Kişisel Bakım"],
  "Buzdolabı Poşeti": ["Ev Bakım"],
  "Krem Peynir ve Labne": ["Süt Ürünleri"],
  "Havlu Kağıt": ["Ev Bakım"],
  "Yumuşatıcı": ["Ev Bakım"],
  "Molfix": ["Bebek"],
  "ELEKTRONİK": ["Teknoloji"],
  "Hazır Çorba": ["Pratik Yemek"],
  "Sinek ve Böcek ilacı": ["Ev Bakım"],
  "Kolonya": ["Kişisel Bakım"],
  "Soğuk Çay ve Kahve": ["Su & İçecek"],
  "Koruyucu Ürünler": ["Kişisel Bakım"],
  "Temizlik Bezi": ["Ev Bakım"],
  "Ağız Bakım Suyu": ["Kişisel Bakım"],
  "KAHVALTILIK": ["Kahvaltılık"],
  "Blendax": ["Kişisel Bakım"],
};

// Kök→yaprak sırayla tam yol. Haritada olmayan adlar tek elemanlı (kendi
// kendinin kökü) yol döner — gelecekte yeni bir alt kategori eklenirse kırılmadan
// düz kök olarak eklenir.
export function resolveCategoryPath(categoryName: string): string[] {
  const ancestors = MARKET_CATEGORY_ANCESTORS[categoryName] ?? [];
  return [...ancestors, categoryName];
}
