import { demoTenants, demoProducts } from "@/lib/demo-data";
import { getDefaultTenantStorefrontSettings } from "@/lib/data";
import type { StorefrontProduct } from "@/lib/types";
function fixture0(){
  const tenant = { ...demoTenants[0], id: "theme-review-electronics", subdomain: "theme-review", company_name: "elektra", sector: "telefon-aksesuar", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Telefon, teknoloji ve aksesuar kataloğu", is_hero_visible: false, is_theme_toggle_visible: true };
  const samples = [{"name": "JBL Flip 6 Taşınabilir Bluetooth Hoparlör", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/050036384384.jpg", "price": 499, "category": "speakers"}, {"name": "JBL HARMAN TUNE 520BT BLUETOOTH KULAKLIK SİYAH", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/050036394963.jpg", "price": 699, "category": "headphones"}, {"name": "JBL HARMAN TUNE 770NC BLUETOOTH KULAKLIK MAVİ", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/050036396028.jpg", "price": 899, "category": "headphones"}, {"name": "JBL Go4 Bluetooth Hoparlör", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/050036399340.jpg", "price": 1099, "category": "speakers"}, {"name": "JBL Junior 320BT Çocuklara Özel Bluetooth Kulaklık", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/050036405546.jpg", "price": 1299, "category": "headphones"}, {"name": "JBL Junior 320BT Çocuklara Özel Kablolu Kulaklık Pembe", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/050036405607.jpg", "price": 1499, "category": "headphones"}];
  const products: StorefrontProduct[] = samples.map((sample, index) => ({ ...demoProducts[0], id: `theme-sample-${index}`, category_id: sample.category, sku_code: `TEK-${1000 + index}`, product_name: sample.name, image_url: sample.image, price: sample.price, package_quantity: 6, carton_quantity: 24, stock_quantity: 48, has_variants: false, variants: [], volume_pricing: null }));
  const categories = [{ id: "headphones", name: "Kulaklıklar" }, { id: "speakers", name: "Hoparlörler" }].map((c, index) => ({ ...c, tenant_id: tenant.id, parent_id: null, banner_item: null, tile_image_url: null, is_discount_category: false, is_hidden_from_storefront: false, display_order: index, created_at: "2026-01-01T00:00:00Z" }));

return {tenant,settings,products,categories};
}
function fixture1(){
  const tenant = { ...demoTenants[0], id: "theme-review-food", subdomain: "theme-review-food", company_name: "sofra", sector: "gida", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Gıda ve içecek kataloğu", is_hero_visible: false, is_theme_toggle_visible: true };
  const samples = [
    {name:"Komili Natürel Sızma Zeytinyağı 500 ml",image:"8699300270002",price:249.90,category:"pantry"},
    {name:"Balparmak Narenciye Balı 460 g",image:"07079673",price:219.90,category:"breakfast"},
    {name:"İçim Süt 1 L",image:"11013025",price:49.90,category:"dairy"},
    {name:"Filiz Burgu Makarna 500 g",image:"5030352",price:29.90,category:"pantry"},
    {name:"Çaykur Rize Turist Çay 1 kg",image:"03111303",price:249.90,category:"drinks"},
    {name:"Duru Pilavlık Bulgur 1 kg",image:"01075029",price:54.90,category:"pantry"},
    {name:"Halis Komili Kekikli Yeşil Zeytin 170 g",image:"16021312",price:79.90,category:"breakfast"},
    {name:"Torku Sütlü Çikolata 60 g",image:"07030995",price:39.90,category:"snacks"},
    {name:"Tamek Domates Salçası 700 g",image:"09010295",price:89.90,category:"cooking"},
    {name:"Eker Ayran 1 L",image:"11550100",price:39.90,category:"dairy"},
    {name:"Torku Tam Yağlı Doğal Yoğurt 750 g",image:"12500201",price:69.90,category:"dairy"},
    {name:"Torku Tam Yulaflı Bisküvi 375 g",image:"07013837",price:44.90,category:"snacks"},
  ];
  const products: StorefrontProduct[] = samples.map((x,i)=>({...demoProducts[0],id:`food-sample-${i}`,category_id:x.category,sku_code:`GDA-${1000+i}`,product_name:x.name,image_url:`https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/${x.image}.jpg`,price:x.price,package_quantity:6,carton_quantity:24,stock_quantity:120,has_variants:false,variants:[],volume_pricing:null,description:"Bu katalog tasarım incelemesi içindir. Fiyatlar örnektir; ürün ve sipariş bilgileri mağaza panelinden yönetilir."}));
  const categories=[{id:"breakfast",name:"Kahvaltılık"},{id:"dairy",name:"Süt & Süt Ürünleri"},{id:"pantry",name:"Temel Gıda"},{id:"drinks",name:"İçecekler"},{id:"snacks",name:"Atıştırmalık"},{id:"cooking",name:"Yemeklik"}].map((c,i)=>({...c,tenant_id:tenant.id,parent_id:null,banner_item:null,tile_image_url:null,is_discount_category:false,is_hidden_from_storefront:false,display_order:i,created_at:"2026-01-01T00:00:00Z"}));

return {tenant,settings,products,categories};
}
function fixture2(){
  const tenant = { ...demoTenants[0], id: "theme-review-textile", subdomain: "theme-review-textile", company_name: "VELIRA", sector: "tekstil", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Giyim ve tekstil kataloğu", is_hero_visible: false, is_theme_toggle_visible: true };
  // Public product photography from the user's demo-giyim catalog; local sample prices and size inventory.
  const samples = [
    {name:"Pudra V Yaka Taş Detaylı Elbise",image:"8181bfb6-c31b-4b63-ad11-5b715c326df1",price:4499,category:"dresses"},
    {name:"Siyah Straplez Drape Detaylı Abiye",image:"d66d4745-f4f8-43e0-b0ba-72508ae2bc47",price:13499,category:"dresses"},
    {name:"Yağ Yeşili Desenli Bol Kesim Gömlek",image:"f89a3040-4496-4eb8-9493-b4e906bf5e50",price:6999,category:"tops"},
    {name:"Zümrüt Pile Detaylı Bol Kesim Pantolon",image:"2e583626-9a68-44ed-be55-a20fe9e043c3",price:4299,category:"bottoms"},
    {name:"Siyah Korsaj Detaylı Midi Boy Etek",image:"c08cc7a6-eb7e-4ed9-a4a1-34b8ef9918c3",price:3999,category:"bottoms"},
    {name:"Siyah Düğme Detaylı Midi Boy Kaban",image:"55abcedd-bc98-4094-9628-7b5f86d1c39c",price:11999,category:"outerwear"},
    {name:"Lila Oversize Baskı Detaylı Sweatshirt",image:"56880669-e670-4a3b-979b-5cc888a1a0dd",price:1699,category:"tops"},
    {name:"Siyah Puantiyeli Ceket",image:"9b0dd95c-7606-48e4-8d86-ee665a4676d5",price:7999,category:"outerwear"},
  ];
  const products: StorefrontProduct[] = samples.map((x,i)=>({...demoProducts[0],id:`textile-sample-${i}`,category_id:x.category,sku_code:`MDL-${1000+i}`,product_name:x.name,image_url:`https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/product-images/adc6dba9-f9de-4548-9163-34cbf4bdb736/products/${x.image}-g.jpg`,image_url_2:null,image_url_3:null,price:x.price,package_quantity:6,carton_quantity:24,stock_quantity:120,has_variants:true,variants:['S','M','L','XL'].map((size,j)=>({id:`textile-${i}-${size}`,product_id:`textile-sample-${i}`,model_name:size,stock_quantity:j===3?0:30,package_quantity:6,carton_quantity:24,is_available_for_sale:j!==3,is_purchasable:j!==3,display_order:j,price:x.price})),volume_pricing:null,description:"Tasarım önizlemesindeki fiyatlar ve beden stokları örnektir. Mağazanızın ürün bilgileri ve satış seçenekleri panelden yönetilir."}));
  const categories=[{id:"dresses",name:"Elbise & Tulum"},{id:"tops",name:"Üst Giyim"},{id:"bottoms",name:"Alt Giyim"},{id:"outerwear",name:"Dış Giyim"}].map((c,i)=>({...c,tenant_id:tenant.id,parent_id:null,banner_item:null,tile_image_url:null,is_discount_category:false,is_hidden_from_storefront:false,display_order:i,created_at:"2026-01-01T00:00:00Z"}));

return {tenant,settings,products,categories};
}
function fixture3(){
  const tenant = { ...demoTenants[0], id: "theme-review-hardware", subdomain: "theme-review-hardware", company_name: "USTA TEDARİK", sector: "hirdavat", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Hırdavat, nalburiye ve yapı kataloğu", is_hero_visible: false, is_theme_toggle_visible: true };
  // Existing catalog photography; prices and inventory below are local demo data.
  const samples = [{"name": "Knitex Şerit Metre 3 M", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44010059.jpg", "category": "measure", "price": 149}, {"name": "Knitex Tornavida Düz 5 x 125", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44010056.jpg", "category": "tools", "price": 89}, {"name": "Evvon Çekiç 100 G", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44010139.jpg", "category": "tools", "price": 179}, {"name": "Knitex Maket Bıçağı Yedekli", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44250079.jpg", "category": "tools", "price": 119}, {"name": "Knitex Sunta Vidası 3.5 x 18 KTX-2607 18'li", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44057251.jpg", "category": "fasteners", "price": 39}, {"name": "Knitex Asma Kilit 30 Mm", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44250087.jpg", "category": "security", "price": 129}, {"name": "Pattex %100 Yapıştırıcı 50 G", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44250909.jpg", "category": "repair", "price": 159}, {"name": "Knitex Metal Duş Hortumu", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/40990137.jpg", "category": "plumbing", "price": 229}];
  const products: StorefrontProduct[] = samples.map((x,i)=>({...demoProducts[0],id:`hardware-sample-${i}`,category_id:x.category,sku_code:`HRD-${1000+i}`,product_name:x.name,image_url:x.image,image_url_2:null,image_url_3:null,price:x.price,package_quantity:6,carton_quantity:24,stock_quantity:120,is_in_stock:true,has_variants:false,variants:[],volume_pricing:null}));
  const categories=[{id:"tools",name:"El Aletleri"},{id:"measure",name:"Ölçüm"},{id:"fasteners",name:"Bağlantı Elemanları"},{id:"security",name:"Kilit & Güvenlik"},{id:"repair",name:"Tamir & Bakım"},{id:"plumbing",name:"Tesisat"}].map((c,i)=>({...c,tenant_id:tenant.id,parent_id:null,banner_item:null,tile_image_url:null,is_discount_category:false,is_hidden_from_storefront:false,display_order:i,created_at:"2026-01-01T00:00:00Z"}));

return {tenant,settings,products,categories};
}
function fixture4(){
  const tenant = { ...demoTenants[0], id: "theme-review-cosmetics", subdomain: "theme-review-cosmetics", company_name: "LUMA BAKIM", sector: "kozmetik", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Kozmetik ve kişisel bakım kataloğu", is_hero_visible: false, is_theme_toggle_visible: true };
  // Existing catalog photography; prices and inventory below are local demo data.
  const samples = [{"name": "NIVEA Aqua Rose Organik Gül Suyu İçeren Nemlendirici Tonik 200 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/35409755.jpg", "category": "skin", "price": 289}, {"name": "Garnier Besleyici Çift Fazlı Micellar Temizleme Suyu 400ML", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/35419836.jpg", "category": "cleanse", "price": 349}, {"name": "Neutrogena Canlandırıcı Yüz Temizleme Jeli 200 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/35410449.jpg", "category": "cleanse", "price": 299}, {"name": "Neutrogena Yoğun Nemlendirici Kavanoz Krem 300 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/35300040.jpg", "category": "body", "price": 249}, {"name": "Maybelline New York Lifter Gloss Nemlendirici Dudak Parlatıcısı - 003 Moon", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/35402129.jpg", "category": "makeup", "price": 329}, {"name": "Gliss Oil Nutritive Sıvı Saç Kremi 200 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/34340122.jpg", "category": "hair", "price": 219}, {"name": "L'Oréal Paris Elseve Collagen Lifter Saç Kremi 250 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/34341478.jpg", "category": "hair", "price": 279}, {"name": "NIVEA SUN SPF30 Güneş Koruyucu ve Nemlendirici Vücut Spreyi 200 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/35520453.jpg", "category": "sun", "price": 549}];
  const products: StorefrontProduct[] = samples.map((x,i)=>({...demoProducts[0],id:`cosmetics-sample-${i}`,category_id:x.category,sku_code:`KZM-${1000+i}`,product_name:x.name,image_url:x.image,image_url_2:null,image_url_3:null,price:x.price,package_quantity:6,carton_quantity:24,stock_quantity:120,is_in_stock:true,has_variants:false,variants:[],volume_pricing:null}));
  const categories=[{id:"skin",name:"Cilt Bakımı"},{id:"cleanse",name:"Temizleme"},{id:"body",name:"Vücut Bakımı"},{id:"makeup",name:"Makyaj"},{id:"hair",name:"Saç Bakımı"},{id:"sun",name:"Güneş Bakımı"}].map((c,i)=>({...c,tenant_id:tenant.id,parent_id:null,banner_item:null,tile_image_url:null,is_discount_category:false,is_hidden_from_storefront:false,display_order:i,created_at:"2026-01-01T00:00:00Z"}));

return {tenant,settings,products,categories};
}
function fixture5(){
  const tenant = { ...demoTenants[0], id: "theme-review-stationery", subdomain: "theme-review-stationery", company_name: "KAĞIT & OYUN", sector: "kirtasiye-oyuncak", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Kırtasiye, okul, hobi ve oyuncak kataloğu", is_hero_visible: false, is_theme_toggle_visible: true };
  // Existing catalog photography; prices and inventory below are local demo data.
  const samples = [{"name": "Faber Castell Kuru Boya Kalemi Redline Metal Tüp 24  Renk", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8690826165247.jpg", "category": "colors", "price": 249}, {"name": "Süpriz Kutu Oyuncak", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8588687348742.jpg", "category": "toys", "price": 149}, {"name": "Çınar Colormaxı A4 72 Yp Kareli Pp Kapak Spiralli Defter", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8695894730021.jpg", "category": "notebooks", "price": 89}, {"name": "Fatih Sulu Boya 12 Renk S-12", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8690216500405.jpg", "category": "colors", "price": 99}, {"name": "Faber Castell  Popart 2B Silgili Kurşun Kalem", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8681241423012.jpg", "category": "pens", "price": 19}, {"name": "Çınar Spiralli Resim Defteri 30yp 24*34 33009", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8695894330092.jpg", "category": "craft", "price": 69}, {"name": "Adel Sulu Boya Seti 12 Renk", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8681241086859.jpg", "category": "colors", "price": 129}, {"name": "Çınar Colormaxi Spiralli Defter A4 40 Yaprak Çizgili", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8695894730168.jpg", "category": "notebooks", "price": 59}];
  const products: StorefrontProduct[] = samples.map((x,i)=>({...demoProducts[0],id:`stationery-sample-${i}`,category_id:x.category,sku_code:`KRT-${1000+i}`,product_name:x.name,image_url:x.image,image_url_2:null,image_url_3:null,price:x.price,package_quantity:6,carton_quantity:24,stock_quantity:120,is_in_stock:true,has_variants:false,variants:[],volume_pricing:null}));
  const categories=[{"id": "colors", "name": "Boya & Renk"}, {"id": "toys", "name": "Oyuncaklar"}, {"id": "notebooks", "name": "Defterler"}, {"id": "pens", "name": "Kalemler"}, {"id": "craft", "name": "Resim & Hobi"}].map((c,i)=>({...c,tenant_id:tenant.id,parent_id:null,banner_item:null,tile_image_url:null,is_discount_category:false,is_hidden_from_storefront:false,display_order:i,created_at:"2026-01-01T00:00:00Z"}));

return {tenant,settings,products,categories};
}
function fixture6(){
  const tenant = { ...demoTenants[0], id: "theme-review-packaging", subdomain: "theme-review-packaging", company_name: "PAK & TEMİZ", sector: "ambalaj", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Ambalaj, paketleme ve temizlik ürünleri", is_hero_visible: false, is_theme_toggle_visible: true };
  // Existing catalog photography; prices and inventory below are local demo data.
  const samples = [{"name": "Koli bandı 100 m", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/2013660000158.jpg", "category": "packing", "price": 39}, {"name": "Cook Eko Streç Film Kayar Bıçak Hediyeli 100 M", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/31203790.jpg", "category": "packing", "price": 129}, {"name": "Ece Party 8 Oz Karton Bardak 10'lu (EPK683)", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/32081910.jpg", "category": "disposable", "price": 49}, {"name": "Netpak Mercan Temalı Kraft Çanta", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/51790796.jpg", "category": "bags", "price": 69}, {"name": "Süper Maylo Bambu Katkılı Kağıt Havlu 16'lı", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/31020084.jpg", "category": "paper", "price": 199}, {"name": "Domestos Yoğun Kıvamlı Yüzey Temizleyici Çam Ferahlığı 1500 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/30719685.jpg", "category": "cleaning", "price": 99}, {"name": "Macromax Mikrofiber Cam Bezi 2'li", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/31163680.jpg", "category": "tools", "price": 89}, {"name": "Koroplast Küçük Boy Çöp Torbası 30'lu", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/31200078.jpg", "category": "bags", "price": 59}, {"name": "Papia Biocare Kağıt Havlu 6'lı", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/31020058.jpg", "category": "paper", "price": 149}, {"name": "Frosch Greyfurt Özlü Mutfak Yüzey Temizleyici 500 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/30719575.jpg", "category": "cleaning", "price": 119}];
  const products: StorefrontProduct[] = samples.map((x,i)=>({...demoProducts[0],id:`packaging-sample-${i}`,category_id:x.category,sku_code:`AMB-${1000+i}`,product_name:x.name,image_url:x.image,image_url_2:null,image_url_3:null,price:x.price,package_quantity:6,carton_quantity:24,stock_quantity:120,is_in_stock:true,has_variants:false,variants:[],volume_pricing:null}));
  const categories=[{"id": "packing", "name": "Bant & Streç"}, {"id": "disposable", "name": "Kullan At"}, {"id": "bags", "name": "Çanta & Torba"}, {"id": "paper", "name": "Kağıt Ürünleri"}, {"id": "cleaning", "name": "Temizlik Ürünleri"}, {"id": "tools", "name": "Temizlik Gereçleri"}].map((c,i)=>({...c,tenant_id:tenant.id,parent_id:null,banner_item:null,tile_image_url:null,is_discount_category:false,is_hidden_from_storefront:false,display_order:i,created_at:"2026-01-01T00:00:00Z"}));

return {tenant,settings,products,categories};
}
function fixture7(){
  const tenant = { ...demoTenants[0], id: "theme-review-electricity", subdomain: "theme-review-electricity", company_name: "IŞIK ELEKTRİK", sector: "elektrik", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Elektrik malzemeleri ve aydınlatma ürünleri", is_hero_visible: false, is_theme_toggle_visible: true };
  // Existing catalog photography; prices and inventory below are local demo data.
  const samples = [{"name": "Panasonic Led Ampul E27 10.5W 1055Lm 4000K", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/39109136.jpg", "category": "bulbs", "price": 89}, {"name": "USB LED MASA LAMBASI", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/2500000104459.jpg", "category": "lamps", "price": 349}, {"name": "Viko Multi-let Siyah Üçlü Priz Topraklı Kablolu 2 M", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/39109230.jpg", "category": "sockets", "price": 279}, {"name": "Nilson Akım Korumalı Beyaz Tekli Fiş Priz", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/39149238.jpg", "category": "protection", "price": 189}, {"name": "Philips Led Ampul 8W E27 6500K Beyaz Işık", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/39100141.jpg", "category": "bulbs", "price": 99}, {"name": "KATLANABİLİR LED MASA LAMBASI", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/6912000242660.jpg", "category": "lamps", "price": 449}, {"name": "Nilson 4'lü Topraklı Anahtarlı Grup Priz 5 Mt Kablo", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/39149233.jpg", "category": "sockets", "price": 399}, {"name": "Fulltech Termal Akım Korumalı Tekli Priz 3xusb", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8681830012405.jpg", "category": "protection", "price": 299}, {"name": "Kodak Led Ampul 9W RGB Kumandalı", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8684641680085.jpg", "category": "bulbs", "price": 199}, {"name": "Led Lityum Koruma Gözlü Masa Lambası", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/6931709041961.jpg", "category": "lamps", "price": 549}, {"name": "Viko Yonca Plus Beyaz Üçlü Topraklı Priz", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/39140012.jpg", "category": "sockets", "price": 159}, {"name": "Nilson Akım Korumalı Beyaz Usbli Fiş Priz", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/39149239.jpg", "category": "protection", "price": 249}];
  const products: StorefrontProduct[] = samples.map((x,i)=>({...demoProducts[0],id:`electricity-sample-${i}`,category_id:x.category,sku_code:`ELK-${1000+i}`,product_name:x.name,image_url:x.image,image_url_2:null,image_url_3:null,price:x.price,package_quantity:6,carton_quantity:24,stock_quantity:120,is_in_stock:true,has_variants:false,variants:[],volume_pricing:null}));
  const categories=[{"id": "bulbs", "name": "LED Ampuller"}, {"id": "lamps", "name": "Masa Lambaları"}, {"id": "sockets", "name": "Grup Prizler"}, {"id": "protection", "name": "Akım Koruma"}].map((c,i)=>({...c,tenant_id:tenant.id,parent_id:null,banner_item:null,tile_image_url:null,is_discount_category:false,is_hidden_from_storefront:false,display_order:i,created_at:"2026-01-01T00:00:00Z"}));

return {tenant,settings,products,categories};
}
function fixture8(){
  const tenant = { ...demoTenants[0], id: "theme-review-homeware", subdomain: "theme-review-homeware", company_name: "EV & SOFRA", sector: "ev-mutfak", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Ev, mutfak ve züccaciye ürünleri", is_hero_visible: false, is_theme_toggle_visible: true };
  // Existing catalog photography; prices and inventory below are local demo data.
  const samples = [{"name": "Keramika Aura Kupa 9 Cm", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/33058884.jpg", "category": "cups", "price": 149}, {"name": "Keramika Marin Servis Tabak 26 Cm", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/33058027.jpg", "category": "table", "price": 249}, {"name": "Mien Bubble Seramik Vazo 21 cm", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8684180921434.jpg", "category": "decor", "price": 399}, {"name": "Tefal Titanyum 2X XL Force Tava 24 Cm", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/32020442.jpg", "category": "cooking", "price": 899}, {"name": "Lav Fresco Saklama Kabı 1150 Cc", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/33030542.jpg", "category": "storage", "price": 189}, {"name": "Paşabahçe Aida Çay Bardağı 6'lı", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/33010014.jpg", "category": "glass", "price": 299}, {"name": "Touch Me Akasya Kase 16X7 Cm", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/32120286.jpg", "category": "table", "price": 349}, {"name": "Touch Me New Bone Soft Kupa 370 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/33054749.jpg", "category": "cups", "price": 129}, {"name": "Paşabahçe Lavinia Crystallin Vazo", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/40310315.jpg", "category": "decor", "price": 449}, {"name": "Papilla Ragnar Wok Tava 28 Cm", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/32020501.jpg", "category": "cooking", "price": 599}, {"name": "Qlux Ideas Bomonti Saklama Kabı Set No:1 4 x 700 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/32088225.jpg", "category": "storage", "price": 229}, {"name": "Paşabahçe Timeless Fincan / Kupa 2'li 315 Cc", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/33030913.jpg", "category": "glass", "price": 349}];
  const products: StorefrontProduct[] = samples.map((x,i)=>({...demoProducts[0],id:`homeware-sample-${i}`,category_id:x.category,sku_code:`EV-${1000+i}`,product_name:x.name,image_url:x.image,image_url_2:null,image_url_3:null,price:x.price,package_quantity:6,carton_quantity:24,stock_quantity:120,is_in_stock:true,has_variants:false,variants:[],volume_pricing:null}));
  const categories=[{"id": "table", "name": "Sofra & Sunum"}, {"id": "cups", "name": "Kupa & Fincan"}, {"id": "glass", "name": "Cam & Bardak"}, {"id": "cooking", "name": "Pişirme"}, {"id": "storage", "name": "Saklama & Düzen"}, {"id": "decor", "name": "Ev Dekorasyonu"}].map((c,i)=>({...c,tenant_id:tenant.id,parent_id:null,banner_item:null,tile_image_url:null,is_discount_category:false,is_hidden_from_storefront:false,display_order:i,created_at:"2026-01-01T00:00:00Z"}));

return {tenant,settings,products,categories};
}
function fixture9(){
  const tenant = { ...demoTenants[0], id: "theme-review-automotive", subdomain: "theme-review-automotive", company_name: "OTO MERKEZ", sector: "yedek-parca", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Otomotiv ve yedek parça ürünleri", is_hero_visible: false, is_theme_toggle_visible: true };
  // Existing catalog photography; prices and inventory below are local demo data.
  const samples = [{"name": "Fren Diski ve Balata Seti · Örnek Ürün", "image": "/temalar/automotive/demo-brake-set.png", "category": "parts", "price": 1490}, {"name": "Robust Oto Silecek 24 İnç 600 Mm 9 Aparatlı", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44516012.jpg", "category": "wipers", "price": 249}, {"name": "Selsil Fren Balata Temizleme Spreyi 500 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44500709.jpg", "category": "maintenance", "price": 129}, {"name": "Carpex Express Oto Cilası 500 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44503333.jpg", "category": "care", "price": 199}, {"name": "Nk 4'lü Oto Takım Kumaş Paspas", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44520103.jpg", "category": "accessories", "price": 499}, {"name": "Autofresh Oto Yazlık Cam Suyu 3 L", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44500633.jpg", "category": "fluids", "price": 99}, {"name": "Robust Oto Silecek 22 İnç 550 Mm 10 Aparatlı", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44516013.jpg", "category": "wipers", "price": 229}, {"name": "Carpex (54002) Oto Şapuanı 1L", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44500606.jpg", "category": "care", "price": 149}, {"name": "Nk Oto Yıkama Eldiveni", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44516008.jpg", "category": "care", "price": 119}, {"name": "Homebasix Oto Şemsiye Güneşlik 130 x 75 Cm", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44510024.jpg", "category": "accessories", "price": 349}, {"name": "Comrade Kışlık Oto Bakım Seti 5'li", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44509519.jpg", "category": "maintenance", "price": 399}, {"name": "Autokit Torpido Yenileme Oto İç Cilası 500 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44549073.jpg", "category": "care", "price": 159}];
  const products: StorefrontProduct[] = samples.map((x,i)=>({...demoProducts[0],id:`automotive-sample-${i}`,category_id:x.category,sku_code:`OTO-${1000+i}`,product_name:x.name,image_url:x.image,image_url_2:null,image_url_3:null,price:x.price,package_quantity:6,carton_quantity:24,stock_quantity:120,is_in_stock:true,has_variants:false,variants:[],volume_pricing:null}));
  const categories=[{"id": "parts", "name": "Yedek Parça"}, {"id": "wipers", "name": "Silecekler"}, {"id": "maintenance", "name": "Bakım Ürünleri"}, {"id": "care", "name": "Temizlik & Cila"}, {"id": "fluids", "name": "Cam Suyu"}, {"id": "accessories", "name": "Aksesuarlar"}].map((c,i)=>({...c,tenant_id:tenant.id,parent_id:null,banner_item:null,tile_image_url:null,is_discount_category:false,is_hidden_from_storefront:false,display_order:i,created_at:"2026-01-01T00:00:00Z"}));

return {tenant,settings,products,categories};
}
function fixture10(){
  const tenant = { ...demoTenants[0], id: "theme-review-general", subdomain: "theme-review-general", company_name: "NOVA TEDARİK", sector: "diger", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Diğer toptan / üretim ürünleri", is_hero_visible: false, is_theme_toggle_visible: true };
  // Existing catalog photography; prices and inventory below are local demo data.
  const samples = [{"name": "Mano Takım Çantası 18'' C.O-18", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8697444382056.jpg", "category": "equipment", "price": 449}, {"name": "Mano Organizer 24 No Vida Kutusu", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8697444381073.jpg", "category": "storage", "price": 249}, {"name": "Koli bandı 100 m", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/2013660000158.jpg", "category": "packing", "price": 39}, {"name": "Knitex Maket Bıçağı Yedekli", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44250079.jpg", "category": "equipment", "price": 89}, {"name": "Koopman Saklama Kutusu 2 Katmanlı Set", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/40310352.jpg", "category": "storage", "price": 299}, {"name": "Ecotape Koli bandı 75 m", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8697641330720.jpg", "category": "packing", "price": 49}, {"name": "Macromax Mikrofiber Cam Bezi 2'li", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/31163680.jpg", "category": "supplies", "price": 99}, {"name": "Knitex Tornavida Düz 5 x 125", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44010056.jpg", "category": "equipment", "price": 119}, {"name": "Tuffex Nice Organizer Kutusu", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/40800113.jpg", "category": "storage", "price": 149}, {"name": "Koroplast Küçük Boy Çöp Torbası 30'lu", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/31200078.jpg", "category": "supplies", "price": 59}, {"name": "Cook Eko Streç Film Kayar Bıçak Hediyeli 100 M", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/31203790.jpg", "category": "packing", "price": 129}, {"name": "Mano Organizer Sarı 7 No", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8697444381028.jpg", "category": "storage", "price": 199}];
  const products: StorefrontProduct[] = samples.map((x,i)=>({...demoProducts[0],id:`general-sample-${i}`,category_id:x.category,sku_code:`NVT-${1000+i}`,product_name:x.name,image_url:x.image,image_url_2:null,image_url_3:null,price:x.price,package_quantity:6,carton_quantity:24,stock_quantity:120,is_in_stock:true,has_variants:false,variants:[],volume_pricing:null}));
  const categories=[{"id": "equipment", "name": "Ekipman & Alet"}, {"id": "storage", "name": "Saklama & Düzen"}, {"id": "packing", "name": "Paketleme"}, {"id": "supplies", "name": "Sarf Malzemeleri"}].map((c,i)=>({...c,tenant_id:tenant.id,parent_id:null,banner_item:null,tile_image_url:null,is_discount_category:false,is_hidden_from_storefront:false,display_order:i,created_at:"2026-01-01T00:00:00Z"}));

return {tenant,settings,products,categories};
}
export const DEMO_FIXTURES: Record<string,typeof fixture0>={"telefon-aksesuar":fixture0,"gida":fixture1,"tekstil":fixture2,"hirdavat":fixture3,"kozmetik":fixture4,"kirtasiye-oyuncak":fixture5,"ambalaj":fixture6,"elektrik":fixture7,"ev-mutfak":fixture8,"yedek-parca":fixture9,"diger":fixture10};
