import { notFound } from "next/navigation";
import { ElectronicsReview } from "@/components/storefront/sector-design/electronics-review";
import { isDesignId, defaultContent } from "@/lib/storefront/sector-design/config";
import { getDefaultTenantStorefrontSettings } from "@/lib/data";
import { demoTenants, demoProducts } from "@/lib/demo-data";
import type { StorefrontProduct } from "@/lib/types";
export const metadata = { title: "Ambalaj ve temizlik tema incelemesi", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";
export default async function PackagingReview({ searchParams }: { searchParams: Promise<{ tema?: string }> }) {
  if (process.env.NODE_ENV !== "development") notFound();
  const { tema } = await searchParams;
  const tenant = { ...demoTenants[0], id: "theme-review-packaging", subdomain: "theme-review-packaging", company_name: "PAK & TEMİZ", sector: "ambalaj", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Ambalaj, paketleme ve temizlik ürünleri", is_hero_visible: false, is_theme_toggle_visible: true };
  // Existing catalog photography; prices and inventory below are local demo data.
  const samples = [{"name": "Koli bandı 100 m", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/2013660000158.jpg", "category": "packing", "price": 39}, {"name": "Cook Eko Streç Film Kayar Bıçak Hediyeli 100 M", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/31203790.jpg", "category": "packing", "price": 129}, {"name": "Ece Party 8 Oz Karton Bardak 10'lu (EPK683)", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/32081910.jpg", "category": "disposable", "price": 49}, {"name": "Netpak Mercan Temalı Kraft Çanta", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/51790796.jpg", "category": "bags", "price": 69}, {"name": "Süper Maylo Bambu Katkılı Kağıt Havlu 16'lı", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/31020084.jpg", "category": "paper", "price": 199}, {"name": "Domestos Yoğun Kıvamlı Yüzey Temizleyici Çam Ferahlığı 1500 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/30719685.jpg", "category": "cleaning", "price": 99}, {"name": "Macromax Mikrofiber Cam Bezi 2'li", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/31163680.jpg", "category": "tools", "price": 89}, {"name": "Koroplast Küçük Boy Çöp Torbası 30'lu", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/31200078.jpg", "category": "bags", "price": 59}, {"name": "Papia Biocare Kağıt Havlu 6'lı", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/31020058.jpg", "category": "paper", "price": 149}, {"name": "Frosch Greyfurt Özlü Mutfak Yüzey Temizleyici 500 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/30719575.jpg", "category": "cleaning", "price": 119}];
  const products: StorefrontProduct[] = samples.map((x,i)=>({...demoProducts[0],id:`packaging-sample-${i}`,category_id:x.category,sku_code:`AMB-${1000+i}`,product_name:x.name,image_url:x.image,image_url_2:null,image_url_3:null,price:x.price,package_quantity:6,carton_quantity:24,stock_quantity:120,is_in_stock:true,has_variants:false,variants:[],volume_pricing:null}));
  const categories=[{"id": "packing", "name": "Bant & Streç"}, {"id": "disposable", "name": "Kullan At"}, {"id": "bags", "name": "Çanta & Torba"}, {"id": "paper", "name": "Kağıt Ürünleri"}, {"id": "cleaning", "name": "Temizlik Ürünleri"}, {"id": "tools", "name": "Temizlik Gereçleri"}].map((c,i)=>({...c,tenant_id:tenant.id,parent_id:null,banner_item:null,tile_image_url:null,is_discount_category:false,is_hidden_from_storefront:false,display_order:i,created_at:"2026-01-01T00:00:00Z"}));
  return <ElectronicsReview tenant={tenant} products={products} categories={categories} settings={settings} contentOverrides={{"packaging-kraft":{...defaultContent("packaging-kraft"),heroCategoryId:"packing",collectionCategoryId:"packing"},"packaging-ferah":{...defaultContent("packaging-ferah"),promoCategoryId:"paper",secondCategoryId:"cleaning"}}} initialTheme={isDesignId(tema) && tema.startsWith("packaging-")?tema:"packaging-kraft"}/>;
}
