"use client";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { ExternalLink } from "lucide-react";
import { designsForSector, type DesignDocument } from "@/lib/storefront/sector-design/config";
export function SectorLiveEditor({ sector, initial, priceLists, previewSrc = "/tema-onizleme", previewOnly = false }: { sector: string; initial: DesignDocument | null; categories: {id:string;name:string}[]; products: {id:string;name:string}[]; priceLists: {id:string;name:string;is_catalog_only:boolean}[]; previewSrc?:string;previewOnly?:boolean }) {
 const router=useRouter();
 useEffect(()=>{const refresh=()=>router.refresh();const changed=(e:StorageEvent)=>{if(e.key==="ekx-theme-published")refresh();};window.addEventListener("focus",refresh);window.addEventListener("storage",changed);return ()=>{window.removeEventListener("focus",refresh);window.removeEventListener("storage",changed);};},[router]);
 const [priceList,setPriceList]=useState(priceLists.find(p=>!p.is_catalog_only)?.id??priceLists[0]?.id??"");
 return <section className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border bg-white p-6"><div><h2 className="text-xl font-semibold text-slate-900">Temanızı seçin, mağazanızın üzerinde düzenleyin</h2><p className="mt-2 max-w-2xl text-sm text-slate-600">Canlı düzenleyici yeni sekmede açılır. Banner ve yazıların üzerine gelin, kaleme tıklayın. Değişiklikler yalnız Kaydet ve yayınla dediğinizde uygulanır.</p>{previewOnly&&<p className="mt-2 text-xs text-amber-800">Bu yerel incelemede örnek ürünler kullanılır; canlı mağazaya kayıt yapılmaz.</p>}</div><label className="text-sm text-slate-700">Önizlenecek fiyat listesi<select value={priceList} onChange={e=>setPriceList(e.target.value)} className="mt-2 block rounded-lg border bg-white p-3">{priceLists.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><div className="grid gap-5 md:grid-cols-3">{designsForSector(sector).map(d=><article key={d.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><a href={`${previewSrc}?edit=1&theme=${d.id}&priceList=${encodeURIComponent(priceList)}`} target="_blank" rel="noopener noreferrer" aria-label={`${d.name} temasını canlı düzenle`} className="block"><img src={`/temalar/${d.id}-desktop.png`} alt={`${d.name} tema önizlemesi`} className="aspect-video w-full object-cover object-top"/><div className="space-y-3 p-5"><div className="flex items-center justify-between"><h3 className="text-xl font-semibold text-slate-900">{d.name}</h3>{initial?.themeId===d.id&&<span className="rounded-full bg-emerald-50 px-3 py-1 text-xs text-emerald-800">Kayıtlı tema</span>}</div><p className="min-h-16 text-sm leading-6 text-slate-600">{d.description}</p><span className="inline-flex items-center gap-2 rounded-lg bg-emerald-800 px-4 py-3 text-sm font-semibold text-white">Canlı düzenle<ExternalLink size={16}/></span></div></a></article>)}</div></section>;
}
