import type {
  AccessCode,
  Category,
  PriceList,
  Product,
  ProductVariant,
  Profile,
  Tenant,
  TenantMembership,
} from "@/lib/types";

const demoProductVariants: ProductVariant[] = [
  {
    id: "var-1-black",
    tenant_id: "tenant-lucatech",
    product_id: "prd-1",
    model_name: "Siyah",
    stock_quantity: 48,
    package_quantity: 12,
    carton_quantity: 48,
    is_available_for_sale: true,
    display_order: 1,
    created_at: new Date("2026-01-10T09:00:00").toISOString(),
    updated_at: new Date("2026-01-10T09:00:00").toISOString(),
  },
  {
    id: "var-1-blue",
    tenant_id: "tenant-lucatech",
    product_id: "prd-1",
    model_name: "Mavi",
    stock_quantity: 0,
    package_quantity: 12,
    carton_quantity: 48,
    is_available_for_sale: false,
    display_order: 2,
    created_at: new Date("2026-01-10T09:10:00").toISOString(),
    updated_at: new Date("2026-01-10T09:10:00").toISOString(),
  },
];

export const demoTenants: Tenant[] = [
  {
    id: "tenant-lucatech",
    company_name: "Lucatech İletişim",
    subdomain: "lucatech",
    status: "active",
    plan: "baslangic",
    max_product_limit: 500,
    whatsapp_number: "905354172510",
    is_whatsapp_order_direct: true,
    custom_domain: null,
    trial_ends_at: null,
    plan_started_at: null,
    plan_expires_at: null,
    visitor_limit_addon: 0,
    visitor_quota_exceeded: false,
    product_limit_addon: 0,
    created_at: new Date("2026-01-01").toISOString(),
  },
  {
    id: "tenant-merkez",
    company_name: "Merkez Toptan",
    subdomain: "merkez",
    status: "suspended",
    plan: "profesyonel",
    max_product_limit: 1000,
    whatsapp_number: "905441112233",
    is_whatsapp_order_direct: true,
    custom_domain: null,
    trial_ends_at: null,
    plan_started_at: null,
    plan_expires_at: null,
    visitor_limit_addon: 0,
    visitor_quota_exceeded: false,
    product_limit_addon: 0,
    created_at: new Date("2026-01-05").toISOString(),
  },
];

export const demoCategories: Category[] = [
  {
    id: "cat-phone",
    tenant_id: "tenant-lucatech",
    name: "Telefonlar",
    parent_id: null,
    display_order: 1,
    banner_item: null,
    created_at: new Date("2026-01-01").toISOString(),
  },
  {
    id: "cat-apple",
    tenant_id: "tenant-lucatech",
    name: "Apple",
    parent_id: "cat-phone",
    display_order: 2,
    banner_item: null,
    created_at: new Date("2026-01-01T12:00:00").toISOString(),
  },
  {
    id: "cat-kampanya",
    tenant_id: "tenant-lucatech",
    name: "Kampanyalı Ürünler",
    parent_id: null,
    display_order: 3,
    banner_item: null,
    created_at: new Date("2026-01-02").toISOString(),
  },
];

export const demoPriceLists: PriceList[] = [
  {
    id: "pl-catalog-lucatech",
    tenant_id: "tenant-lucatech",
    name: "Fiyatsız Katalog",
    is_catalog_only: true,
    sort_order: 0,
    created_at: new Date("2026-01-01").toISOString(),
  },
  {
    id: "pl-1-lucatech",
    tenant_id: "tenant-lucatech",
    name: "1.Liste",
    is_catalog_only: false,
    sort_order: 1,
    created_at: new Date("2026-01-01").toISOString(),
  },
  {
    id: "pl-2-lucatech",
    tenant_id: "tenant-lucatech",
    name: "2.Liste",
    is_catalog_only: false,
    sort_order: 2,
    created_at: new Date("2026-01-01").toISOString(),
  },
  {
    id: "pl-3-lucatech",
    tenant_id: "tenant-lucatech",
    name: "3.Liste",
    is_catalog_only: false,
    sort_order: 3,
    created_at: new Date("2026-01-01").toISOString(),
  },
];

export const demoProducts: Product[] = [
  {
    id: "prd-1",
    tenant_id: "tenant-lucatech",
    category_id: "cat-apple",
    display_order: 1,
    sku_code: "APL-IPH-15-128",
    product_name: "iPhone 15 128GB",
    image_url:
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=900&q=80",
    currency: "TRY",
    prices: [
      { product_id: "prd-1", price_list_id: "pl-1-lucatech", price: 41250 },
      { product_id: "prd-1", price_list_id: "pl-2-lucatech", price: 41890 },
      { product_id: "prd-1", price_list_id: "pl-3-lucatech", price: 42390 },
    ],
    is_in_stock: true,
    is_discount_active: false,
    discount_price: null,
    package_quantity: 20,
    carton_quantity: 200,
    created_at: new Date("2026-01-10").toISOString(),
    variants: demoProductVariants.filter((variant) => variant.product_id === "prd-1"),
  },
  {
    id: "prd-2",
    tenant_id: "tenant-lucatech",
    category_id: "cat-phone",
    display_order: 2,
    sku_code: "SMS-S24-256",
    product_name: "Samsung S24 256GB",
    image_url:
      "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=900&q=80",
    currency: "TRY",
    prices: [
      { product_id: "prd-2", price_list_id: "pl-1-lucatech", price: 35890 },
      { product_id: "prd-2", price_list_id: "pl-2-lucatech", price: 36490 },
      { product_id: "prd-2", price_list_id: "pl-3-lucatech", price: 36990 },
    ],
    is_in_stock: true,
    is_discount_active: false,
    discount_price: null,
    package_quantity: null,
    carton_quantity: null,
    created_at: new Date("2026-01-11").toISOString(),
  },
  {
    id: "prd-3",
    tenant_id: "tenant-lucatech",
    category_id: "cat-kampanya",
    display_order: 3,
    sku_code: "XIA-RED-13",
    product_name: "Redmi Note 13",
    image_url:
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80",
    currency: "TRY",
    prices: [
      { product_id: "prd-3", price_list_id: "pl-1-lucatech", price: 10350 },
      { product_id: "prd-3", price_list_id: "pl-2-lucatech", price: 10750 },
      { product_id: "prd-3", price_list_id: "pl-3-lucatech", price: 10990 },
    ],
    is_in_stock: false,
    is_discount_active: false,
    discount_price: null,
    package_quantity: 10,
    carton_quantity: null,
    created_at: new Date("2026-01-12").toISOString(),
  },
];

export const demoAccessCodes: AccessCode[] = [
  {
    id: "acc-1",
    tenant_id: "tenant-lucatech",
    password_code: "1111",
    price_list_id: "pl-1-lucatech",
    price_list_name: "1.Liste",
    created_at: new Date("2026-01-10").toISOString(),
  },
  {
    id: "acc-2",
    tenant_id: "tenant-lucatech",
    password_code: "2222",
    price_list_id: "pl-2-lucatech",
    price_list_name: "2.Liste",
    created_at: new Date("2026-01-10").toISOString(),
  },
  {
    id: "acc-3",
    tenant_id: "tenant-lucatech",
    password_code: "3333",
    price_list_id: "pl-3-lucatech",
    price_list_name: "3.Liste",
    created_at: new Date("2026-01-10").toISOString(),
  },
  {
    id: "acc-4",
    tenant_id: "tenant-lucatech",
    password_code: "0000",
    price_list_id: "pl-catalog-lucatech",
    price_list_name: "Fiyatsız Katalog",
    created_at: new Date("2026-01-10").toISOString(),
  },
];

export const demoProfiles: Profile[] = [
  {
    id: "demo-super-admin",
    full_name: "Süper Admin",
    role: "super_admin",
    must_change_password: false,
    created_at: new Date("2026-01-01").toISOString(),
  },
];

export const demoMemberships: TenantMembership[] = [
  {
    id: "membership-1",
    tenant_id: "tenant-lucatech",
    user_id: "demo-tenant-admin",
    created_at: new Date("2026-01-01").toISOString(),
  },
];