import { notFound } from "next/navigation";
import { ElectronicsReview } from "@/components/storefront/sector-design/electronics-review";
import { isDesignId } from "@/lib/storefront/sector-design/config";
import { getDefaultTenantStorefrontSettings } from "@/lib/data";
import { demoTenants, demoProducts } from "@/lib/demo-data";
import type { StorefrontProduct } from "@/lib/types";
export const metadata = { title: "Kozmetik tema incelemesi", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";
export default async function CosmeticsReview({ searchParams }: { searchParams: Promise<{ tema?: string }> }) {
  if (process.env.NODE_ENV !== "development") notFound();
  const { tema } = await searchParams;
  const tenant = { ...demoTenants[0], id: "theme-review-cosmetics", subdomain: "theme-review-cosmetics", company_name: "LUMA BAKIM", sector: "kozmetik", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Kozmetik ve kişisel bakım kataloğu", is_hero_visible: false, is_theme_toggle_visible: true };
  // Existing catalog photography; prices and inventory below are local demo data.
  const samples = [{"name": "NIVEA Aqua Rose Organik Gül Suyu İçeren Nemlendirici Tonik 200 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/35409755.jpg", "category": "skin", "price": 289}, {"name": "Garnier Besleyici Çift Fazlı Micellar Temizleme Suyu 400ML", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/35419836.jpg", "category": "cleanse", "price": 349}, {"name": "Neutrogena Canlandırıcı Yüz Temizleme Jeli 200 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/35410449.jpg", "category": "cleanse", "price": 299}, {"name": "Neutrogena Yoğun Nemlendirici Kavanoz Krem 300 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/35300040.jpg", "category": "body", "price": 249}, {"name": "Maybelline New York Lifter Gloss Nemlendirici Dudak Parlatıcısı - 003 Moon", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/35402129.jpg", "category": "makeup", "price": 329}, {"name": "Gliss Oil Nutritive Sıvı Saç Kremi 200 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/34340122.jpg", "category": "hair", "price": 219}, {"name": "L'Oréal Paris Elseve Collagen Lifter Saç Kremi 250 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/34341478.jpg", "category": "hair", "price": 279}, {"name": "NIVEA SUN SPF30 Güneş Koruyucu ve Nemlendirici Vücut Spreyi 200 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/35520453.jpg", "category": "sun", "price": 549}];
  const products: StorefrontProduct[] = samples.map((x,i)=>({...demoProducts[0],id:`cosmetics-sample-${i}`,category_id:x.category,sku_code:`KZM-${1000+i}`,product_name:x.name,image_url:x.image,image_url_2:null,image_url_3:null,price:x.price,package_quantity:6,carton_quantity:24,stock_quantity:120,is_in_stock:true,has_variants:false,variants:[],volume_pricing:null}));
  const categories=[{id:"skin",name:"Cilt Bakımı"},{id:"cleanse",name:"Temizleme"},{id:"body",name:"Vücut Bakımı"},{id:"makeup",name:"Makyaj"},{id:"hair",name:"Saç Bakımı"},{id:"sun",name:"Güneş Bakımı"}].map((c,i)=>({...c,tenant_id:tenant.id,parent_id:null,banner_item:null,tile_image_url:null,is_discount_category:false,is_hidden_from_storefront:false,display_order:i,created_at:"2026-01-01T00:00:00Z"}));
  return <ElectronicsReview tenant={tenant} products={products} categories={categories} settings={settings} initialTheme={isDesignId(tema) && tema.startsWith("cosmetics-")?tema:"cosmetics-duru"}/>;
}
