import { notFound } from "next/navigation";
import { ElectronicsReview } from "@/components/storefront/sector-design/electronics-review";
import { isDesignId, defaultContent } from "@/lib/storefront/sector-design/config";
import { getDefaultTenantStorefrontSettings } from "@/lib/data";
import { demoTenants, demoProducts } from "@/lib/demo-data";
import type { StorefrontProduct } from "@/lib/types";
export const metadata = { title: "Diğer toptan / üretim tema incelemesi", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";
export default async function GeneralReview({ searchParams }: { searchParams: Promise<{ tema?: string }> }) {
  if (process.env.NODE_ENV !== "development") notFound();
  const { tema } = await searchParams;
  const tenant = { ...demoTenants[0], id: "theme-review-general", subdomain: "theme-review-general", company_name: "NOVA TEDARİK", sector: "diger", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Diğer toptan / üretim ürünleri", is_hero_visible: false, is_theme_toggle_visible: true };
  // Existing catalog photography; prices and inventory below are local demo data.
  const samples = [{"name": "Mano Takım Çantası 18'' C.O-18", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8697444382056.jpg", "category": "equipment", "price": 449}, {"name": "Mano Organizer 24 No Vida Kutusu", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8697444381073.jpg", "category": "storage", "price": 249}, {"name": "Koli bandı 100 m", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/2013660000158.jpg", "category": "packing", "price": 39}, {"name": "Knitex Maket Bıçağı Yedekli", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44250079.jpg", "category": "equipment", "price": 89}, {"name": "Koopman Saklama Kutusu 2 Katmanlı Set", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/40310352.jpg", "category": "storage", "price": 299}, {"name": "Ecotape Koli bandı 75 m", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8697641330720.jpg", "category": "packing", "price": 49}, {"name": "Macromax Mikrofiber Cam Bezi 2'li", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/31163680.jpg", "category": "supplies", "price": 99}, {"name": "Knitex Tornavida Düz 5 x 125", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44010056.jpg", "category": "equipment", "price": 119}, {"name": "Tuffex Nice Organizer Kutusu", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/40800113.jpg", "category": "storage", "price": 149}, {"name": "Koroplast Küçük Boy Çöp Torbası 30'lu", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/31200078.jpg", "category": "supplies", "price": 59}, {"name": "Cook Eko Streç Film Kayar Bıçak Hediyeli 100 M", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/31203790.jpg", "category": "packing", "price": 129}, {"name": "Mano Organizer Sarı 7 No", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/8697444381028.jpg", "category": "storage", "price": 199}];
  const products: StorefrontProduct[] = samples.map((x,i)=>({...demoProducts[0],id:`general-sample-${i}`,category_id:x.category,sku_code:`NVT-${1000+i}`,product_name:x.name,image_url:x.image,image_url_2:null,image_url_3:null,price:x.price,package_quantity:6,carton_quantity:24,stock_quantity:120,is_in_stock:true,has_variants:false,variants:[],volume_pricing:null}));
  const categories=[{"id": "equipment", "name": "Ekipman & Alet"}, {"id": "storage", "name": "Saklama & Düzen"}, {"id": "packing", "name": "Paketleme"}, {"id": "supplies", "name": "Sarf Malzemeleri"}].map((c,i)=>({...c,tenant_id:tenant.id,parent_id:null,banner_item:null,tile_image_url:null,is_discount_category:false,is_hidden_from_storefront:false,display_order:i,created_at:"2026-01-01T00:00:00Z"}));
  return <ElectronicsReview tenant={tenant} products={products} categories={categories} settings={settings} contentOverrides={{"general-atlas":{...defaultContent("general-atlas"),heroCategoryId:"all",collectionCategoryId:"equipment"},"general-odak":{...defaultContent("general-odak"),promoCategoryId:"storage",secondCategoryId:"supplies"}}} initialTheme={isDesignId(tema) && tema.startsWith("general-")?tema:"general-atlas"}/>;
}
