import { notFound } from "next/navigation";
import { ElectronicsReview } from "@/components/storefront/sector-design/electronics-review";
import { isDesignId, defaultContent } from "@/lib/storefront/sector-design/config";
import { getDefaultTenantStorefrontSettings } from "@/lib/data";
import { demoTenants, demoProducts } from "@/lib/demo-data";
import type { StorefrontProduct } from "@/lib/types";
export const metadata = { title: "Otomotiv ve yedek parça tema incelemesi", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";
export default async function AutomotiveReview({ searchParams }: { searchParams: Promise<{ tema?: string }> }) {
  if (process.env.NODE_ENV !== "development") notFound();
  const { tema } = await searchParams;
  const tenant = { ...demoTenants[0], id: "theme-review-automotive", subdomain: "theme-review-automotive", company_name: "OTO MERKEZ", sector: "yedek-parca", whatsapp_number: "", is_demo: true };
  const settings = { ...getDefaultTenantStorefrontSettings(tenant.id), storefront_title: tenant.company_name, storefront_description: "Otomotiv ve yedek parça ürünleri", is_hero_visible: false, is_theme_toggle_visible: true };
  // Existing catalog photography; prices and inventory below are local demo data.
  const samples = [{"name": "Fren Diski ve Balata Seti · Örnek Ürün", "image": "/temalar/automotive/demo-brake-set.png", "category": "parts", "price": 1490}, {"name": "Robust Oto Silecek 24 İnç 600 Mm 9 Aparatlı", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44516012.jpg", "category": "wipers", "price": 249}, {"name": "Selsil Fren Balata Temizleme Spreyi 500 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44500709.jpg", "category": "maintenance", "price": 129}, {"name": "Carpex Express Oto Cilası 500 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44503333.jpg", "category": "care", "price": 199}, {"name": "Nk 4'lü Oto Takım Kumaş Paspas", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44520103.jpg", "category": "accessories", "price": 499}, {"name": "Autofresh Oto Yazlık Cam Suyu 3 L", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44500633.jpg", "category": "fluids", "price": 99}, {"name": "Robust Oto Silecek 22 İnç 550 Mm 10 Aparatlı", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44516013.jpg", "category": "wipers", "price": 229}, {"name": "Carpex (54002) Oto Şapuanı 1L", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44500606.jpg", "category": "care", "price": 149}, {"name": "Nk Oto Yıkama Eldiveni", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44516008.jpg", "category": "care", "price": 119}, {"name": "Homebasix Oto Şemsiye Güneşlik 130 x 75 Cm", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44510024.jpg", "category": "accessories", "price": 349}, {"name": "Comrade Kışlık Oto Bakım Seti 5'li", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44509519.jpg", "category": "maintenance", "price": 399}, {"name": "Autokit Torpido Yenileme Oto İç Cilası 500 Ml", "image": "https://mfsjzivcsvrxuegqzafe.supabase.co/storage/v1/object/public/market-catalog-images/44549073.jpg", "category": "care", "price": 159}];
  const products: StorefrontProduct[] = samples.map((x,i)=>({...demoProducts[0],id:`automotive-sample-${i}`,category_id:x.category,sku_code:`OTO-${1000+i}`,product_name:x.name,image_url:x.image,image_url_2:null,image_url_3:null,price:x.price,package_quantity:6,carton_quantity:24,stock_quantity:120,is_in_stock:true,has_variants:false,variants:[],volume_pricing:null}));
  const categories=[{"id": "parts", "name": "Yedek Parça"}, {"id": "wipers", "name": "Silecekler"}, {"id": "maintenance", "name": "Bakım Ürünleri"}, {"id": "care", "name": "Temizlik & Cila"}, {"id": "fluids", "name": "Cam Suyu"}, {"id": "accessories", "name": "Aksesuarlar"}].map((c,i)=>({...c,tenant_id:tenant.id,parent_id:null,banner_item:null,tile_image_url:null,is_discount_category:false,is_hidden_from_storefront:false,display_order:i,created_at:"2026-01-01T00:00:00Z"}));
  return <ElectronicsReview tenant={tenant} products={products} categories={categories} settings={settings} contentOverrides={{"automotive-apex":{...defaultContent("automotive-apex"),heroCategoryId:"all",collectionCategoryId:"care"},"automotive-garaj":{...defaultContent("automotive-garaj"),promoCategoryId:"wipers",secondCategoryId:"care"}}} initialTheme={isDesignId(tema) && tema.startsWith("automotive-")?tema:"automotive-apex"}/>;
}
